{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-json",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-json-metadata-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-json-0.3.3-SNAPSHOT.jar",
          "size": 18800,
          "sha512": "f4285a96527253af68a7ea1dc4e5dc3d7a11f493aa6948d925b06e68633ba15f396ca4621d673b0588b8a5be34d746467e9288e97a83b30901f9e52c4bedefbe",
          "sha256": "2ce6911038aa4ae2f1f3944ea14bbdd8c7fb47a63ddcb845e19027ce5f10bd27",
          "sha1": "a9d91486dfbb900f1fd665d5ab9db75f159e2cff",
          "md5": "7854fa78a18ddd4eea28f82011a3c7b2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-schema-json-kotlin-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-json-0.3.3-SNAPSHOT-sources.jar",
          "size": 27709,
          "sha512": "7d45f144625940c6cc32c87b23061518b61d1acfb5fdb83d92f6e8fa78d7599a5e621daddea545b1231e0c5ba499ace297df2b2ef62372bc6d3c725dbf06fded",
          "sha256": "b0266ad5c0c964c542b8bf319f3510c219ea66a0bc0bb3488e9a315618a17b16",
          "sha1": "4a9693ee4e62b074aa315f67b2b72948c822b9b5",
          "md5": "5db25762770b5adb345cc085b69f94b2"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-js/0.3.3-SNAPSHOT/kotlinx-schema-json-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-js/0.3.3-SNAPSHOT/kotlinx-schema-json-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-js/0.3.3-SNAPSHOT/kotlinx-schema-json-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-jvm/0.3.3-SNAPSHOT/kotlinx-schema-json-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-jvm/0.3.3-SNAPSHOT/kotlinx-schema-json-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-jvm/0.3.3-SNAPSHOT/kotlinx-schema-json-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-linuxarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-linuxarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-linuxarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-linuxarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-linuxarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-linuxarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-linuxx64/0.3.3-SNAPSHOT/kotlinx-schema-json-linuxx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-linuxx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-linuxx64/0.3.3-SNAPSHOT/kotlinx-schema-json-linuxx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-linuxx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-mingwx64/0.3.3-SNAPSHOT/kotlinx-schema-json-mingwx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-mingwx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-mingwx64/0.3.3-SNAPSHOT/kotlinx-schema-json-mingwx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-mingwx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-json-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-json-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-json-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    }
  ]
}
