package ai.koog.prompt.executor.model

import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.LLMChoice
import ai.koog.prompt.message.Message
import ai.koog.prompt.streaming.StreamFrame
import ai.koog.prompt.structure.json.generator.BasicJsonSchemaGenerator
import ai.koog.prompt.structure.json.generator.StandardJsonSchemaGenerator
import kotlinx.coroutines.flow.Flow

/**
 * API for [PromptExecutor].
 */
public interface PromptExecutorAPI : AutoCloseable {
    /**
     * Executes [prompt] using model selected by [modelSelector] and optional [tools].
     *
     * The executor passes its available models to [modelSelector], which ranks them.
     * [policy] controls how many ranked models are attempted and how failures are handled.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @param policy Execution policy for retries and fallback across selected models.
     * @return Responses generated by execution.
     */
    public suspend fun execute(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
        policy: ExecutionPolicy = ExecutionPolicy.Default,
    ): List<Message.Response>

    /**
     * Executes [prompt] using [model] and [tools].
     *
     * This overload delegates to [execute] with [ModelSelectors.specific].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param model Model used for execution.
     * @param tools Tools available during execution.
     * @return Responses generated by execution.
     */
    public suspend fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor> = emptyList()
    ): List<Message.Response> =
        execute(
            prompt = prompt,
            modelSelector = ModelSelectors.specific(model),
            tools = tools,
            policy = ExecutionPolicy.Default,
        )

    /**
     * Executes [prompt] using model selected by [modelSelector] and streams output frames.
     *
     * The executor passes its available models to [modelSelector], which ranks them.
     * [policy] controls how many ranked models are attempted and how failures are handled.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @param policy Execution policy for retries and fallback across selected models.
     * @return Stream of model output frames.
     */
    public fun executeStreaming(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
        policy: ExecutionPolicy = ExecutionPolicy.Default,
    ): Flow<StreamFrame>

    /**
     * Executes [prompt] using [model] and streams output frames.
     *
     * This overload delegates to [executeStreaming] with [ModelSelectors.specific].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param model Model used for execution.
     * @param tools Tools available during execution.
     * @return Stream of model output frames.
     */
    public fun executeStreaming(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor> = emptyList()
    ): Flow<StreamFrame> =
        executeStreaming(
            prompt = prompt,
            modelSelector = ModelSelectors.specific(model),
            tools = tools,
            policy = ExecutionPolicy.Default,
        )

    /**
     * Receives multiple independent choices for [prompt] using a [ModelSelector].
     *
     * Implemented only for providers that support multiple choices.
     * The executor passes its available models to [modelSelector], which ranks them.
     * [policy] controls how many ranked models are attempted and how failures are handled.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @param policy Execution policy for retries and fallback across selected models.
     * @return Generated model choices.
     */
    public suspend fun executeMultipleChoices(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor>,
        policy: ExecutionPolicy = ExecutionPolicy.Default,
    ): List<LLMChoice>

    /**
     * Receives multiple independent choices for [prompt] using [model].
     *
     * This overload delegates to [executeMultipleChoices] with [ModelSelectors.specific].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param model Model used for execution.
     * @param tools Tools available during execution.
     * @return Generated model choices.
     */
    public suspend fun executeMultipleChoices(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): List<LLMChoice> =
        executeMultipleChoices(
            prompt = prompt,
            modelSelector = ModelSelectors.specific(model),
            tools = tools,
            policy = ExecutionPolicy.Default,
        )

    /**
     * Moderates [prompt] using model selected by [modelSelector].
     *
     * The executor passes its available models to [modelSelector], which ranks them.
     * [policy] controls how many ranked models are attempted and how failures are handled.
     *
     * @param prompt Prompt containing content to moderate.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param policy Execution policy for retries and fallback across selected models.
     * @return Moderation result.
     */
    public suspend fun moderate(
        prompt: Prompt,
        modelSelector: ModelSelector,
        policy: ExecutionPolicy = ExecutionPolicy.Default,
    ): ModerationResult

    /**
     * Moderates [prompt] using [model].
     *
     * This overload delegates to [moderate] with [ModelSelectors.specific].
     *
     * @param prompt Prompt containing content to moderate.
     * @param model Model used for moderation.
     * @return Moderation result.
     */
    public suspend fun moderate(prompt: Prompt, model: LLModel): ModerationResult =
        moderate(
            prompt = prompt,
            modelSelector = ModelSelectors.specific(model),
            policy = ExecutionPolicy.Default,
        )

    /**
     * Retrieves all models available for this executor.
     *
     * @return Available models.
     * @throws UnsupportedOperationException If the executor does not expose model discovery.
     */
    public suspend fun models(): List<LLModel> {
        throw UnsupportedOperationException("Not implemented for this executor")
    }

    /**
     * Returns standard JSON schema generator for [model].
     *
     * Default implementation returns [StandardJsonSchemaGenerator].
     *
     * @param model Model for which schema generator is requested.
     * @return Standard JSON schema generator.
     */
    public fun getStandardJsonSchemaGenerator(model: LLModel): StandardJsonSchemaGenerator {
        return StandardJsonSchemaGenerator
    }

    /**
     * Returns basic JSON schema generator for [model].
     *
     * Default implementation returns [BasicJsonSchemaGenerator].
     *
     * @param model Model for which schema generator is requested.
     * @return Basic JSON schema generator.
     */
    public fun getBasicJsonSchemaGenerator(model: LLModel): BasicJsonSchemaGenerator {
        return BasicJsonSchemaGenerator
    }
}
