package ai.koog.prompt.executor.model

import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.LLMChoice
import ai.koog.prompt.message.Message
import ai.koog.prompt.streaming.StreamFrame
import kotlinx.coroutines.flow.Flow

/**
 * Abstract base for executors that support model selection via [ModelSelector].
 *
 * Extends [PromptExecutor] with a [ModelSelector]-based execution API and makes [models]
 * mandatory so that selectors receive a non-empty candidate list. This class provides the
 * model-based [PromptExecutorAPI] overrides, delegating each call to the corresponding
 * [ModelSelector] variant via [ModelSelectors.specific]. Concrete subclasses only need to
 * implement the [ModelSelector] variants (primary dispatch).
 *
 * Currently used by
 * [RoutingLLMPromptExecutor][ai.koog.prompt.executor.llms.RoutingLLMPromptExecutor].
 */
public abstract class SelectingPromptExecutor : PromptExecutor() {

    override suspend fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): List<Message.Response> = execute(prompt, ModelSelectors.specific(model), tools)

    override fun executeStreaming(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): Flow<StreamFrame> = executeStreaming(prompt, ModelSelectors.specific(model), tools)

    override suspend fun executeMultipleChoices(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): List<LLMChoice> = executeMultipleChoices(prompt, ModelSelectors.specific(model), tools)

    override suspend fun moderate(prompt: Prompt, model: LLModel): ModerationResult =
        moderate(prompt, ModelSelectors.specific(model))

    /**
     * Executes [prompt] using the model chosen by [modelSelector].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Responses generated by execution.
     */
    public abstract suspend fun execute(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
        executionPolicy: ExecutionPolicy = ExecutionPolicy.TryBestOnce,
    ): List<Message.Response>

    /**
     * Executes [prompt] using the model chosen by [modelSelector] and streams output frames.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Stream of model output frames.
     */
    public abstract fun executeStreaming(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
        executionPolicy: ExecutionPolicy = ExecutionPolicy.TryBestOnce,
    ): Flow<StreamFrame>

    /**
     * Receives multiple independent choices for [prompt] using the model chosen by [modelSelector].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Generated model choices.
     */
    public abstract suspend fun executeMultipleChoices(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor>,
        executionPolicy: ExecutionPolicy = ExecutionPolicy.TryBestOnce,
    ): List<LLMChoice>

    /**
     * Moderates [prompt] using the model chosen by [modelSelector].
     *
     * @param prompt Prompt containing content to moderate.
     * @param modelSelector Selector that ranks models available to this executor.
     * @return Moderation result.
     */
    public abstract suspend fun moderate(
        prompt: Prompt,
        modelSelector: ModelSelector,
        executionPolicy: ExecutionPolicy = ExecutionPolicy.TryBestOnce
    ): ModerationResult

    /**
     * Returns all models available to this executor.
     *
     * Called by [ModelSelector.select] to provide the candidate list for selection.
     * Implementations are encouraged to cache this result to avoid repeated network round-trips.
     *
     * @return Available models.
     */
    abstract override suspend fun models(): List<LLModel>
}

/**
 * Defines how execution should traverse and retry models returned by a [ModelSelector].
 *
 * @constructor Creates immutable execution policy.
 * @property modelsToAttempt Maximum number of models returned by [ModelSelector.select] that may be attempted.
 * @property maxRetriesPerModel Maximum retries per attempted model.
 * @throws IllegalArgumentException If [maxRetriesPerModel] is negative.
 */
public data class ExecutionPolicy(
    public val modelsToAttempt: ModelsToAttempt = ModelsToAttempt.UpTo(1),
    public val maxRetriesPerModel: Int = 0,
) {

    init {
        require(maxRetriesPerModel >= 0) { "maxRetriesPerModel must be non-negative." }
    }

    public companion object {
        public val TryBestOnce: ExecutionPolicy = ExecutionPolicy(
            modelsToAttempt = ModelsToAttempt.UpTo(1),
            maxRetriesPerModel = 0,
        )

        public val TryAllOnce: ExecutionPolicy = ExecutionPolicy(
            modelsToAttempt = ModelsToAttempt.All,
            maxRetriesPerModel = 0,
        )
    }
}

/**
 * Limit for how many ranked models can be attempted for a single execution.
 */
public sealed interface ModelsToAttempt {

    /**
     * Attempt all models from selector ranking.
     */
    public object All : ModelsToAttempt

    /**
     * Attempt up to [count] models from selector ranking.
     *
     * @constructor Creates bounded-attempt limit.
     * @property count Maximum number of models to attempt.
     * @throws IllegalArgumentException If [count] is not positive.
     */
    public data class UpTo(val count: Int) : ModelsToAttempt {
        init {
            require(count > 0) { "count must be positive, was $count" }
        }
    }
}
