package ai.koog.prompt.executor.model

import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.LLMChoice
import ai.koog.prompt.message.Message
import ai.koog.prompt.streaming.StreamFrame
import kotlinx.coroutines.flow.Flow

/**
 * Abstract base for executors that support model selection via [ModelSelector].
 *
 * Extends [PromptExecutor] with a [ModelSelector]-based execution API and makes [models]
 * mandatory so that selectors receive a non-empty candidate list.
 *
 * This class provides the model-based [PromptExecutorAPI] overrides, delegating each call to the corresponding
 * [ModelSelector] variant via [ModelSelectors.specific].
 *
 * Concrete subclasses must implement the [ModelSelector] variants (primary dispatch) and [models] (candidates source).
 */
public abstract class SelectingPromptExecutor : PromptExecutor() {

    override suspend fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): List<Message.Response> = execute(prompt, ModelSelectors.specific(model), tools)

    override fun executeStreaming(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): Flow<StreamFrame> = executeStreaming(prompt, ModelSelectors.specific(model), tools)

    override suspend fun executeMultipleChoices(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): List<LLMChoice> = executeMultipleChoices(prompt, ModelSelectors.specific(model), tools)

    override suspend fun moderate(prompt: Prompt, model: LLModel): ModerationResult =
        moderate(prompt, ModelSelectors.specific(model))

    /**
     * Executes [prompt] using the model chosen by [modelSelector].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Responses generated by execution.
     */
    public abstract suspend fun execute(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
    ): List<Message.Response>

    /**
     * Executes [prompt] using the model chosen by [modelSelector] and streams output frames.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Stream of model output frames.
     */
    public abstract fun executeStreaming(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
    ): Flow<StreamFrame>

    /**
     * Receives multiple independent choices for [prompt] using the model chosen by [modelSelector].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Generated model choices.
     */
    public abstract suspend fun executeMultipleChoices(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
    ): List<LLMChoice>

    /**
     * Moderates [prompt] using the model chosen by [modelSelector].
     *
     * @param prompt Prompt containing content to moderate.
     * @param modelSelector Selector that ranks models available to this executor.
     * @return Moderation result.
     */
    public abstract suspend fun moderate(prompt: Prompt, modelSelector: ModelSelector): ModerationResult

    /**
     * Returns all models available to this executor.
     *
     * It is intended to be used along [ModelSelector.select] to provide the candidate list for selection.
     *
     * @return Available models.
     */
    abstract override suspend fun models(): List<LLModel>
}
