{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-ksp-gradle-plugin",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-ksp-gradle-plugin-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-ksp-gradle-plugin-0.3.3-SNAPSHOT.jar",
          "size": 42462,
          "sha512": "8f40bb7deda2169ca3eb61c2f798f7fb1e79fa9f0617dcb3888bb3682c59a022f9949cb05ee0a7eca35356d9ef21b810fd3a832ca1dac8ae186dd7dd2ee18c95",
          "sha256": "e33ebcf2a8ba470c08d45bbfed6bd0708b9b08d2d3ef1f5327b4d824cebee290",
          "sha1": "22ae73e04942c769564d4f1283f460e3a0c811be",
          "md5": "2ad245af968cd8a2998f6da09de85f73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.6"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-aa-embeddable",
          "version": {
            "requires": "2.3.6"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.3.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-ksp-gradle-plugin-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-ksp-gradle-plugin-0.3.3-SNAPSHOT.jar",
          "size": 42462,
          "sha512": "8f40bb7deda2169ca3eb61c2f798f7fb1e79fa9f0617dcb3888bb3682c59a022f9949cb05ee0a7eca35356d9ef21b810fd3a832ca1dac8ae186dd7dd2ee18c95",
          "sha256": "e33ebcf2a8ba470c08d45bbfed6bd0708b9b08d2d3ef1f5327b4d824cebee290",
          "sha1": "22ae73e04942c769564d4f1283f460e3a0c811be",
          "md5": "2ad245af968cd8a2998f6da09de85f73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinx-schema-ksp-gradle-plugin-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-ksp-gradle-plugin-0.3.3-SNAPSHOT-sources.jar",
          "size": 11612,
          "sha512": "892032f6440958faafe210c0cb7281dd4f2886b1d87b395e4ecfd6bc3fef9648bf3e6a12994437df3b7c6b893777f1c23ad7e230afecf37413e66203d4913cfd",
          "sha256": "50eb10b0c27c7196b5f2b4ffb1f8af009e66c7da67cff2907853c6e207bfc227",
          "sha1": "2549d0d61e72f915945cace79fda0b4fd10ccffd",
          "md5": "6e41eb63a5e91bfebe4bab3ae8d4ad31"
        }
      ]
    }
  ]
}
