{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-generator-json/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-json",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-generator-core",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-json",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT.jar",
          "size": 65526,
          "sha512": "793a767df24756663f7f7e4f09889dd88ff448e424b35182de124adc69286228ddad438aa57542ace60772707f7072591245e13ff0beb6de1f56137b6429f3db",
          "sha256": "51b294d4ced7c023f8cc59e958ee409ce7f1e6b0b901fae9d1b19e5bffe3de9c",
          "sha1": "9291fdf65bf71c27b099baf4cac27b3dfc983498",
          "md5": "00f3ca104fcc7fee323fef3b5ea9e918"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-generator-core",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-json",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT.jar",
          "size": 65526,
          "sha512": "793a767df24756663f7f7e4f09889dd88ff448e424b35182de124adc69286228ddad438aa57542ace60772707f7072591245e13ff0beb6de1f56137b6429f3db",
          "sha256": "51b294d4ced7c023f8cc59e958ee409ce7f1e6b0b901fae9d1b19e5bffe3de9c",
          "sha1": "9291fdf65bf71c27b099baf4cac27b3dfc983498",
          "md5": "00f3ca104fcc7fee323fef3b5ea9e918"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT-sources.jar",
          "size": 23472,
          "sha512": "a487760d92ae0aaa08408884d9ae80b6bb0d1abca640f2251a633b3c801b247e838a3b8aa781151eb1e1cc0548c951099726ae6c7256703693a75c5c559f1a64",
          "sha256": "896b5687d76b5e49d6e7905ffe2d0ae1bd2c5ba27732421f86439645a2114c59",
          "sha1": "f90f5955a118e5fd924bb0cfff52f2fdee1f13de",
          "md5": "d126991f83a1ce7710cb8d0bca156147"
        }
      ]
    }
  ]
}
