{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-annotations/0.3.3-SNAPSHOT/kotlinx-schema-annotations-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-annotations",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-annotations-macosArm64Main-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-annotations-macosarm64-0.3.3-SNAPSHOT.klib",
          "size": 6066,
          "sha512": "516c764b59209a22d36ac55b2d00acdf0540fc2b27dfa47bf15329ad701a4ca3563a7c4bdf251c6026957eb2e2e877f6e5f9ddb99b73b2ff4274a40a8f9ee30c",
          "sha256": "b31e58b9e1d0285323f963c8fffa882e8790506285142e4bbbf96564e261fd6f",
          "sha1": "300351e15efc2b9c41da61afee5e6cb2506c9650",
          "md5": "23073185b8b64e3d80903dfd393a1dab"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-schema-annotations-macosarm64-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-annotations-macosarm64-0.3.3-SNAPSHOT-sources.jar",
          "size": 1631,
          "sha512": "0bcef48a7152f5f3ed20bb514b48ff724882a157b6a25ed2be11722507fa0c858edf12c156b3b3fb8909d4e8fd3044ed5dd827dadb1fde947545c746444121f2",
          "sha256": "215d4ec2ac4e47149a09f48ef61395a1b4d3cb545590f861874934be3a9d069c",
          "sha1": "d3ffba1dbddbacb053361e482b29ab71441b8768",
          "md5": "3c9c0aacf4945cf6f1f1021d38987725"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-annotations-macosarm64-0.3.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-schema-annotations-macosarm64-0.3.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
