{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-generator-json/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-json",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-generator-core",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-json",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-json-macosArm64Main-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-generator-json-macosarm64-0.3.3-SNAPSHOT.klib",
          "size": 78971,
          "sha512": "52f5d3e264a299b8e1ba647cc1e311ccda9677e5925fe19f01c073685d73ff85f6b92c6d8f388ba5d6046926b4989610168dbc21db3598d970ca1a0ec18c476f",
          "sha256": "b9f96b21bf8c058f3ff58b7688c956e49bbd0a95e0b29abdc3508afd6f1b5426",
          "sha1": "80bd52ed349ebf5ccb1a105777843d1cbd3afdd3",
          "md5": "0d1556c0e2694a2f2e7debb0307a330c"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-json-macosarm64-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-json-macosarm64-0.3.3-SNAPSHOT-sources.jar",
          "size": 19683,
          "sha512": "357f1227fe71824ffa8d4b42af5ac67a5af520b00f851b819dbabe1cdfc478ecaa59f9d6552e5add4e6d908b14faae16521c27258b35d67dd418660a976d34c3",
          "sha256": "1460a400b213aed030f072bf7ce267907e9e7e7bf9768019da78afdeb7e4077d",
          "sha1": "d7fa5b158e8eb64cd53fc26056bdc53e14bc8ba3",
          "md5": "db04f032cfa18b9e8771b0091a9e3867"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-generator-core",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-json",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-json-macosarm64-0.3.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-schema-generator-json-macosarm64-0.3.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
