{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-generator-core/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-core",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT.klib",
          "size": 34391,
          "sha512": "a4b449b4b6e9455f76bfc6a2a3a1ee4f7178c3669d92105a00de9a0acffd1c6772a1c92e2bc6c22ee84c7725c777c1c66d61f4644e9a08b76db3f4b2e2c65e00",
          "sha256": "38b387f743a3a1fb648a69dc5a9a9cc41e6525d84eae823cd4f506d8d1140829",
          "sha1": "66629b45458661df8ebbbc6b72c869004c1e9cba",
          "md5": "5f361d0477baaebb7e32d7caaaea3d5e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT.klib",
          "size": 34391,
          "sha512": "a4b449b4b6e9455f76bfc6a2a3a1ee4f7178c3669d92105a00de9a0acffd1c6772a1c92e2bc6c22ee84c7725c777c1c66d61f4644e9a08b76db3f4b2e2c65e00",
          "sha256": "38b387f743a3a1fb648a69dc5a9a9cc41e6525d84eae823cd4f506d8d1140829",
          "sha1": "66629b45458661df8ebbbc6b72c869004c1e9cba",
          "md5": "5f361d0477baaebb7e32d7caaaea3d5e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT-sources.jar",
          "size": 11235,
          "sha512": "45a37de25b8da704151900243cdf2494e4f60e01c95361ec58f2dc6e4f8eb4b62236dc2d3ee72ca34fee91b0a7f1e59676fe3899b85a087bf44b6a2405c0e6c8",
          "sha256": "3aae8f956e9ebdd5a4745df868ac424b011ccd6ab7e8ca736f5948bd651a5946",
          "sha1": "f2f6f2f183b3aeec8f1985eadfa0156807141f8b",
          "md5": "0e00cc88d587dc148be8b9df8133c7b0"
        }
      ]
    }
  ]
}
