{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-annotations/0.3.3-SNAPSHOT/kotlinx-schema-annotations-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-annotations",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-annotations-mingwX64Main-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-annotations-mingwx64-0.3.3-SNAPSHOT.klib",
          "size": 6055,
          "sha512": "43956ff5afc87936c52158ac8b1301bba1fb6015bbb7292c9390b52aac3fbee231e57db2ae8ef5a5833b5d5eff2477e21981d450d2b99597fc797e78d7517b5c",
          "sha256": "192809eab226a322444269079c992a92779112a1fda56728114703477d40f2c1",
          "sha1": "e49eaa7fe4cacf5c4c80970f9b726724b44bbb14",
          "md5": "be318cf4c864475852f846105fe23468"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-schema-annotations-mingwx64-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-annotations-mingwx64-0.3.3-SNAPSHOT-sources.jar",
          "size": 1631,
          "sha512": "0bcef48a7152f5f3ed20bb514b48ff724882a157b6a25ed2be11722507fa0c858edf12c156b3b3fb8909d4e8fd3044ed5dd827dadb1fde947545c746444121f2",
          "sha256": "215d4ec2ac4e47149a09f48ef61395a1b4d3cb545590f861874934be3a9d069c",
          "sha1": "d3ffba1dbddbacb053361e482b29ab71441b8768",
          "md5": "3c9c0aacf4945cf6f1f1021d38987725"
        }
      ]
    }
  ]
}
