{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-json/0.3.3-SNAPSHOT/kotlinx-schema-json-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-json",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT.klib",
          "size": 332657,
          "sha512": "910956f6094df67852e47639f5ac8df29d764667addee9164a1b77eb136766e945731fd9f0e2bfb2edee92779c6df6a053f1464155d8c029e427a21c24aac609",
          "sha256": "96345bb0ce6d8adab15890b23baeb650503a6c7734084d5801eba57d91485531",
          "sha1": "d101549c4ee5cb7b4f49e07f18577811dd1d6c59",
          "md5": "05e2f9ad2eedc9543755acd19b306ce5"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT.klib",
          "size": 332657,
          "sha512": "910956f6094df67852e47639f5ac8df29d764667addee9164a1b77eb136766e945731fd9f0e2bfb2edee92779c6df6a053f1464155d8c029e427a21c24aac609",
          "sha256": "96345bb0ce6d8adab15890b23baeb650503a6c7734084d5801eba57d91485531",
          "sha1": "d101549c4ee5cb7b4f49e07f18577811dd1d6c59",
          "md5": "05e2f9ad2eedc9543755acd19b306ce5"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-json-wasm-js-0.3.3-SNAPSHOT-sources.jar",
          "size": 27709,
          "sha512": "7d45f144625940c6cc32c87b23061518b61d1acfb5fdb83d92f6e8fa78d7599a5e621daddea545b1231e0c5ba499ace297df2b2ef62372bc6d3c725dbf06fded",
          "sha256": "b0266ad5c0c964c542b8bf319f3510c219ea66a0bc0bb3488e9a315618a17b16",
          "sha1": "4a9693ee4e62b074aa315f67b2b72948c822b9b5",
          "md5": "5db25762770b5adb345cc085b69f94b2"
        }
      ]
    }
  ]
}
