{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-annotations/0.3.3-SNAPSHOT/kotlinx-schema-annotations-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-annotations",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-annotations-jvm-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-annotations-jvm-0.3.3-SNAPSHOT.jar",
          "size": 2152,
          "sha512": "ecfbc2d507fe7c26fafdbb752d676633326dbe991963e7815154d75e32e6494f259da95f9ae3027baf5c6708d6800bd56477b7579bc79c9dd62962824e3931ac",
          "sha256": "60e84db88364dad1a99533b69dc4afa0cda3fafc7d59bb390b2a7d5ca9f00432",
          "sha1": "a2fa7c25d94da737c0b1092dd352645d95cb6182",
          "md5": "c3b3f46e12e9da747d39e02d2b6544fc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-annotations-jvm-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-annotations-jvm-0.3.3-SNAPSHOT.jar",
          "size": 2152,
          "sha512": "ecfbc2d507fe7c26fafdbb752d676633326dbe991963e7815154d75e32e6494f259da95f9ae3027baf5c6708d6800bd56477b7579bc79c9dd62962824e3931ac",
          "sha256": "60e84db88364dad1a99533b69dc4afa0cda3fafc7d59bb390b2a7d5ca9f00432",
          "sha1": "a2fa7c25d94da737c0b1092dd352645d95cb6182",
          "md5": "c3b3f46e12e9da747d39e02d2b6544fc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-schema-annotations-jvm-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-annotations-jvm-0.3.3-SNAPSHOT-sources.jar",
          "size": 1631,
          "sha512": "0bcef48a7152f5f3ed20bb514b48ff724882a157b6a25ed2be11722507fa0c858edf12c156b3b3fb8909d4e8fd3044ed5dd827dadb1fde947545c746444121f2",
          "sha256": "215d4ec2ac4e47149a09f48ef61395a1b4d3cb545590f861874934be3a9d069c",
          "sha1": "d3ffba1dbddbacb053361e482b29ab71441b8768",
          "md5": "3c9c0aacf4945cf6f1f1021d38987725"
        }
      ]
    }
  ]
}
