{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-generator-core/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-core",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-watchosArm32Main-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-generator-core-watchosarm32-0.3.3-SNAPSHOT.klib",
          "size": 39465,
          "sha512": "22ed0a859adfcd0205c34f67fad92e011d7dc068d146a0d6dace2c664b0a5400f03287c6b7d92f591903e68d77eccba290e4c4d9c8fb0870cb0fd343d748d66e",
          "sha256": "28fa97580cf5c28c10edb8ddb3dc9811e5cf2d562e4c5b54363d52f8588a98d6",
          "sha1": "ee435c4feccfc3cd1ef36ef738b80c8e0a9b8e53",
          "md5": "382a81ea79e1e746f7d2b696b050f28d"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-core-watchosarm32-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-core-watchosarm32-0.3.3-SNAPSHOT-sources.jar",
          "size": 11277,
          "sha512": "269bd266e0b42e6f92f4cb86d10f7b5f019b29bd8ffabdbb2a85f74b2c9c6520b13fbfd86f6818751f7569e8f40c6cfa49f6c009bf3c87609cddce545c829d3b",
          "sha256": "00baf7bbae0bbd1909617490c5cb129498aca2827443e447ba80a6afaaf724d3",
          "sha1": "1e61f1361475152527619eabe3e16134a55e8d88",
          "md5": "08bcf0baca4ff5a0a07cf7a3c6c6da28"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-watchosarm32-0.3.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-schema-generator-core-watchosarm32-0.3.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
