{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-ksp",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-ksp-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-ksp-0.3.3-SNAPSHOT.jar",
          "size": 75066,
          "sha512": "3505fefb925014feae4c45098f77263a834bfabce0fc2041f6cdc71dd6c31279e65fb9199c021dce56a4c23855c77870e2c24f31836811ff97da3d8477db362d",
          "sha256": "23810cc1f0eaec48bde476d25ad6448a0d4177b3a8e3bad46af023d074c5c3f1",
          "sha1": "7a2ca095ceecff43c6a311a539355c62f3d1237c",
          "md5": "f00904daabbb7a010c72cd4ed1d9f64d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-generator-json",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-ksp-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-ksp-0.3.3-SNAPSHOT.jar",
          "size": 75066,
          "sha512": "3505fefb925014feae4c45098f77263a834bfabce0fc2041f6cdc71dd6c31279e65fb9199c021dce56a4c23855c77870e2c24f31836811ff97da3d8477db362d",
          "sha256": "23810cc1f0eaec48bde476d25ad6448a0d4177b3a8e3bad46af023d074c5c3f1",
          "sha1": "7a2ca095ceecff43c6a311a539355c62f3d1237c",
          "md5": "f00904daabbb7a010c72cd4ed1d9f64d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinx-schema-ksp-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-ksp-0.3.3-SNAPSHOT-sources.jar",
          "size": 33596,
          "sha512": "b754b106340bf77428eb3078a0bbb334252d2e335461557cd0ff587393a1137ec7da47503e35cb5d4beab12a4fe53b8dbfb34625651ae72937b4602a036a53dd",
          "sha256": "11f33e25c04138171860bbb9bb20727d59e12f22037687944fc1006c28b01f6d",
          "sha1": "5b89071770c1a6cf6c865050d7f2d2bcde276ffe",
          "md5": "f743fcdc683f40244b587062702bcda6"
        }
      ]
    }
  ]
}
