package ai.koog.prompt.executor.llms

import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.executor.model.PromptExecutor
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.Message
import ai.koog.prompt.message.ResponseMetaInfo
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.datetime.Clock

/**
 * Mock implementation of PromptExecutor for testing and examples.
 * 
 * This executor provides predictable responses without requiring real LLM API calls,
 * making it perfect for:
 * - Running examples without API keys
 * - Testing applications that use Koog
 * - Development environments
 * - CI/CD pipelines
 * 
 * @param responseConfig Configuration for mock responses
 */
public class MockPromptExecutor(
    public val responseConfig: MockResponseConfig = MockResponseConfig()
) : PromptExecutor {
    
    /**
     * Configuration for mock responses.
     * Allows mapping input patterns to specific responses for predictable testing.
     */
    public class MockResponseConfig {
        private val responses = mutableMapOf<String, String>()
        private val defaultResponse = "This is a mock response from MockPromptExecutor. " +
                "In a real application, this would be generated by an LLM."
        
        /**
         * Add a response for prompts containing the specified pattern.
         * 
         * @param pattern Text pattern to match in prompts (case-insensitive)
         * @param response Response to return when pattern is found
         */
        public fun addResponse(pattern: String, response: String) {
            responses[pattern.lowercase()] = response
        }
        
        /**
         * Add multiple response mappings at once.
         * 
         * @param mappings Map of patterns to responses
         */
        public fun addResponses(mappings: Map<String, String>) {
            mappings.forEach { (pattern, response) ->
                addResponse(pattern, response)
            }
        }
        
        /**
         * Get the appropriate response for a given prompt.
         * Searches for the first matching pattern in the order they were added.
         * 
         * @param prompt The prompt to find a response for
         * @return Matching response or default response if no pattern matches
         */
        public fun getResponse(prompt: String): String {
            val lowerPrompt = prompt.lowercase()
            
            // Find first matching pattern
            val matchingResponse = responses.entries.firstOrNull { (pattern, _) ->
                lowerPrompt.contains(pattern)
            }?.value
            
            return matchingResponse ?: defaultResponse
        }
        
        /**
         * Clear all configured responses.
         */
        public fun clear() {
            responses.clear()
        }
        
        /**
         * Get all configured response patterns.
         */
        public fun getPatterns(): Set<String> = responses.keys.toSet()
    }
    
    override suspend fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): List<Message.Response> {
        val promptText = prompt.toString()
        val responseText = responseConfig.getResponse(promptText)
        
        // Create mock assistant message
        val assistantMessage = Message.Assistant(
            content = responseText,
            metaInfo = ResponseMetaInfo(
                timestamp = Clock.System.now(),
                totalTokensCount = responseText.length / 4, // Rough token estimation
                inputTokensCount = promptText.length / 4,
                outputTokensCount = responseText.length / 4
            )
        )
        
        return listOf(assistantMessage)
    }
    
    override suspend fun executeStreaming(prompt: Prompt, model: LLModel): Flow<String> {
        val promptText = prompt.toString()
        val responseText = responseConfig.getResponse(promptText)
        return flowOf(responseText)
    }
    
    override suspend fun moderate(prompt: Prompt, model: LLModel): ModerationResult {
        // Mock moderation always passes
        return ModerationResult(
            isHarmful = false,
            categories = emptyMap()
        )
    }
    
    public companion object {
        /**
         * Create a MockPromptExecutor with common default responses for examples.
         * 
         * @return Configured MockPromptExecutor with typical example responses
         */
        public fun withExampleResponses(): MockPromptExecutor {
            return MockPromptExecutor().apply {
                responseConfig.addResponses(mapOf(
                    "search" to "Found 10 relevant results for your search query.",
                    "database" to "Database operation completed successfully.",
                    "admin" to "Administrative command executed successfully.", 
                    "report" to "Report has been generated and is ready for review.",
                    "analyze" to "Analysis completed. Here are the key findings...",
                    "create" to "Resource has been created successfully.",
                    "update" to "Resource has been updated successfully.",
                    "delete" to "Resource has been deleted successfully.",
                    "list" to "Here are the requested items...",
                    "help" to "Here's how I can help you with that task...",
                    "guest" to "Task completed for guest user.",
                    "user" to "Task completed for authenticated user.",
                    "premium" to "Task completed for premium user.",
                    "hello" to "Hello! How can I help you today?"
                ))
            }
        }
        
        /**
         * Create a MockPromptExecutor with test-specific responses.
         * 
         * @return Configured MockPromptExecutor with predictable test responses
         */
        public fun withTestResponses(): MockPromptExecutor {
            return MockPromptExecutor().apply {
                responseConfig.addResponses(mapOf(
                    "test" to "TEST_RESPONSE",
                    "search" to "TEST_SEARCH_RESULT", 
                    "database" to "TEST_DATABASE_RESULT",
                    "admin" to "TEST_ADMIN_RESULT",
                    "error" to "TEST_ERROR_SIMULATION",
                    "guest" to "Mock response for guest role",
                    "user" to "Mock response for user role"
                ))
            }
        }
    }
}