{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-annotations/0.3.3-SNAPSHOT/kotlinx-schema-annotations-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-annotations",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-annotations-tvosArm64Main-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-annotations-tvosarm64-0.3.3-SNAPSHOT.klib",
          "size": 6060,
          "sha512": "1e93204fb153ace9fbceac5864605e6d46386264c36a5ae0330b240fae6b7c0939f4ef43efb620683114d35818b8865f8d7b9ca8d3f87cb35d060a66c2578e8c",
          "sha256": "cc4a73df0e8c9ec968e12074b1b9c9e792e97c8b41a5aa22f5bec9b94e29368b",
          "sha1": "b38bcc9cc954b7c1598c5adc6f3f6364121c2a8a",
          "md5": "2a6aafbb96f47bb1a9610da854412edc"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-schema-annotations-tvosarm64-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-annotations-tvosarm64-0.3.3-SNAPSHOT-sources.jar",
          "size": 1631,
          "sha512": "0bcef48a7152f5f3ed20bb514b48ff724882a157b6a25ed2be11722507fa0c858edf12c156b3b3fb8909d4e8fd3044ed5dd827dadb1fde947545c746444121f2",
          "sha256": "215d4ec2ac4e47149a09f48ef61395a1b4d3cb545590f861874934be3a9d069c",
          "sha1": "d3ffba1dbddbacb053361e482b29ab71441b8768",
          "md5": "3c9c0aacf4945cf6f1f1021d38987725"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-annotations-tvosarm64-0.3.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-schema-annotations-tvosarm64-0.3.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
