{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-generator-core/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-core",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-watchosX64Main-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-generator-core-watchosx64-0.3.3-SNAPSHOT.klib",
          "size": 39454,
          "sha512": "a4d3c206949a040f01561a424d7288cb6c732a475203282bd9f5f5e66bfe4ec136a7444eae302d9da452fca67db45ba91f2c6bf5109534f2f61dfc69d0e2706b",
          "sha256": "6e3deb2f2c6ae7a7bfcedc029be55e8428418532c5400fb0cc136ddf5867e9bf",
          "sha1": "6c0d593873571ff2e767e5e45884cfe3bf60d452",
          "md5": "a3519043b011dd6ae2fe76cf1fdb3d2c"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-core-watchosx64-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-core-watchosx64-0.3.3-SNAPSHOT-sources.jar",
          "size": 11277,
          "sha512": "269bd266e0b42e6f92f4cb86d10f7b5f019b29bd8ffabdbb2a85f74b2c9c6520b13fbfd86f6818751f7569e8f40c6cfa49f6c009bf3c87609cddce545c829d3b",
          "sha256": "00baf7bbae0bbd1909617490c5cb129498aca2827443e447ba80a6afaaf724d3",
          "sha1": "1e61f1361475152527619eabe3e16134a55e8d88",
          "md5": "08bcf0baca4ff5a0a07cf7a3c6c6da28"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-watchosx64-0.3.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-schema-generator-core-watchosx64-0.3.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
