{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-generator-core/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-core",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT.jar",
          "size": 74294,
          "sha512": "4dbfffadcfbee06292614e559ee5f7f87fa84f8d03921ae7ec7a448a3b9adab22c8055ed693b22ba612dd5d574f4ff50c3bbe4736278c56645a8ba2b8d4c99bf",
          "sha256": "5ffba7a1e438fe081c5be251c4dd926e23461081bce6b5605965aa9efd6ea06d",
          "sha1": "9d807e4edf7a38e231df18de4b0270aeb4e30916",
          "md5": "fc0943a9f8279ef5ea66875e98fa859c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT.jar",
          "size": 74294,
          "sha512": "4dbfffadcfbee06292614e559ee5f7f87fa84f8d03921ae7ec7a448a3b9adab22c8055ed693b22ba612dd5d574f4ff50c3bbe4736278c56645a8ba2b8d4c99bf",
          "sha256": "5ffba7a1e438fe081c5be251c4dd926e23461081bce6b5605965aa9efd6ea06d",
          "sha1": "9d807e4edf7a38e231df18de4b0270aeb4e30916",
          "md5": "fc0943a9f8279ef5ea66875e98fa859c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT-sources.jar",
          "size": 22599,
          "sha512": "44e672e9fb4c7a79373583c890fe97e5ae7fd1d1d9e215de1aa522800746aecf0c7b9653737e9b8b31ab342b33839a9ad41e6fdd2cd9d949b2fb2dd52edae986",
          "sha256": "da4787a3363879ec987b0efd6404e6d24dc84807642246d866e7b1562147838a",
          "sha1": "c06677859defd5e52bac30012070668df51edb93",
          "md5": "47ec21546002e228dea3e10dc2477d99"
        }
      ]
    }
  ]
}
