package ai.koog.agents.core.feature.model.events

import ai.koog.agents.core.agent.execution.AgentExecutionInfo
import ai.koog.agents.core.feature.model.AIAgentError
import ai.koog.serialization.JSONElement
import ai.koog.utils.time.KoogClock
import kotlin.time.Duration
import kotlinx.serialization.Serializable

/**
 * Represents an event triggered when the execution of a specific subgraph starts.
 *
 * This event captures the initiation of a subgraph execution, including details
 * such as the unique run identifier, the name of the subgraph, and the input data
 * provided to the subgraph.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId Unique identifier for the subgraph run;
 * @property subgraphName The name of the subgraph being executed;
 * @property input The input data provided to the subgraph;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class SubgraphExecutionStartingEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val subgraphName: String,
    val input: JSONElement?,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent() {

    /**
     * @deprecated Use constructor with [executionInfo] parameter
     */
    @Deprecated(
        message = "Use constructor with executionInfo parameter",
        replaceWith = ReplaceWith("SubgraphExecutionStartingEvent(executionInfo, runId, subgraphName, input, timestamp)")
    )
    public constructor(
        runId: String,
        subgraphName: String,
        input: JSONElement?,
        timestamp: Long = KoogClock.System.now().toEpochMilliseconds()
    ) : this(
        eventId = SubgraphExecutionStartingEvent::class.simpleName.toString(),
        executionInfo = AgentExecutionInfo(
            parent = null,
            partName = SubgraphExecutionStartingEvent::class.simpleName.toString(),
        ),
        runId = runId,
        subgraphName = subgraphName,
        input = input,
        timestamp = timestamp
    )
}

/**
 * Represents an event triggered when the execution of a specific subgraph completes.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId Unique identifier for the subgraph run;
 * @property subgraphName The name of the subgraph being executed;
 * @property input The input data provided to the subgraph;
 * @property output The output data generated by the subgraph;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 * @property duration Elapsed time of the subgraph's body execution. See
 * `SubgraphExecutionCompletedContext.duration` for full semantics.
 */
@Serializable
public data class SubgraphExecutionCompletedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val subgraphName: String,
    val input: JSONElement?,
    val output: JSONElement?,
    val duration: Duration,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent() {

    /**
     * @deprecated Use constructor with [executionInfo] parameter
     */
    @Deprecated(
        message = "Use constructor with executionInfo parameter",
        replaceWith = ReplaceWith("SubgraphExecutionCompletedEvent(executionInfo, runId, subgraphName, input, output, duration, timestamp)")
    )
    public constructor(
        runId: String,
        subgraphName: String,
        input: JSONElement?,
        output: JSONElement?,
        duration: Duration,
        timestamp: Long = KoogClock.System.now().toEpochMilliseconds()
    ) : this(
        eventId = SubgraphExecutionCompletedEvent::class.simpleName.toString(),
        executionInfo = AgentExecutionInfo(
            parent = null,
            partName = SubgraphExecutionCompletedEvent::class.simpleName.toString(),
        ),
        runId = runId,
        subgraphName = subgraphName,
        input = input,
        output = output,
        duration = duration,
        timestamp = timestamp,
    )
}

/**
 * Represents an event triggered when the execution of a specific subgraph fails.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId Unique identifier for the subgraph run;
 * @property subgraphName The name of the subgraph being executed;
 * @property input The input data provided to the subgraph;
 * @property error The error that occurred during the subgraph execution;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 * @property duration Elapsed time of the subgraph's body execution up to the failure. See
 * `SubgraphExecutionFailedContext.duration` for full semantics.
 */
@Serializable
public data class SubgraphExecutionFailedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val subgraphName: String,
    val input: JSONElement?,
    val error: AIAgentError,
    val duration: Duration,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent() {

    /**
     * @deprecated Use constructor with [executionInfo] parameter
     */
    @Deprecated(
        message = "Use constructor with executionInfo parameter",
        replaceWith = ReplaceWith("SubgraphExecutionFailedEvent(executionInfo, runId, subgraphName, input, error, duration, timestamp)")
    )
    public constructor(
        runId: String,
        subgraphName: String,
        input: JSONElement?,
        error: AIAgentError,
        duration: Duration,
        timestamp: Long = KoogClock.System.now().toEpochMilliseconds()
    ) : this(
        eventId = SubgraphExecutionFailedEvent::class.simpleName.toString(),
        executionInfo = AgentExecutionInfo(
            parent = null,
            partName = SubgraphExecutionFailedEvent::class.simpleName.toString(),
        ),
        runId = runId,
        subgraphName = subgraphName,
        input = input,
        error = error,
        duration = duration,
        timestamp = timestamp,
    )
}
