package ai.koog.prompt.executor.selection

import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.executor.model.PromptExecutorAPI
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.LLMChoice
import ai.koog.prompt.message.Message
import ai.koog.prompt.streaming.StreamFrame
import kotlinx.coroutines.flow.Flow

/**
 * API for prompt executors that support model selection via [ModelSelector].
 *
 * Extends [ai.koog.prompt.executor.model.PromptExecutor] with a [ModelSelector]-based execution API and makes [models]
 * mandatory so that selectors receive a non-empty candidate list.
 *
 * This interface provides the model-based [ai.koog.prompt.executor.model.PromptExecutor] overrides, delegating each call to the corresponding
 * [ModelSelector] variant via [ModelSelectors.specific].
 *
 * Concrete implementations must implement the [ModelSelector] variants (primary dispatch) and [models] (candidates source).
 */
public interface SelectingPromptExecutorAPI : PromptExecutorAPI {

    // region PromptExecutorAPI overrides
    override suspend fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): List<Message.Response> = execute(prompt, ModelSelectors.specific(model), tools)

    override fun executeStreaming(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): Flow<StreamFrame> = executeStreaming(prompt, ModelSelectors.specific(model), tools)

    override suspend fun executeMultipleChoices(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>
    ): List<LLMChoice> = executeMultipleChoices(prompt, ModelSelectors.specific(model), tools)

    override suspend fun moderate(prompt: Prompt, model: LLModel): ModerationResult =
        moderate(prompt, ModelSelectors.specific(model))
    // endregion

    // region ModelSelector-based API

    /**
     * Executes [prompt] using the model chosen by [modelSelector].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Responses generated by execution.
     */
    public suspend fun execute(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
    ): List<Message.Response>

    /**
     * Executes [prompt] using the model chosen by [modelSelector] and streams output frames.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Stream of model output frames.
     */
    public fun executeStreaming(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
    ): Flow<StreamFrame>

    /**
     * Receives multiple independent choices for [prompt] using the model chosen by [modelSelector].
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return Generated model choices.
     */
    public suspend fun executeMultipleChoices(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
    ): List<LLMChoice>

    /**
     * Moderates the content of a given message with attachments using a specified LLM.
     *
     * This method evaluates the content of the message and its attachments to determine
     * if it complies with content guidelines. The moderation is performed using the model(s) suggested by the
     * [modelSelector], which analyzes the content and returns a detailed moderation result.
     *
     * @param prompt Prompt containing content to moderate.
     * @param modelSelector Selector that ranks models available to this executor.
     * @return A `ModerationResult` containing information about the moderation outcome,
     *         including flagged categories, scores, and whether the content is classified
     *         as harmful.
     */
    public suspend fun moderate(prompt: Prompt, modelSelector: ModelSelector): ModerationResult

    /**
     * Retrieves a list of available models from all LLM clients managed by this executor.
     *
     * This method aggregates models from all configured LLM providers and clients,
     * returning a comprehensive list of available language models that can be used
     * with this executor.
     *
     * Implementing this method is required — it serves as the source of truth for model selection.
     *
     * @return A list of [LLModel] instances representing all available models.
     */
    public override suspend fun models(): List<LLModel>
    // endregion
}
