package ai.koog.agents.core.agent

import ai.koog.agents.core.agent.context.AIAgentContext

/**
 * Represents the contextual result produced by an AI agent after processing, encapsulating both the output
 * and the contextual information associated with the agent's execution.
 *
 * @param TOutput The type of the output generated by the AI agent.
 * @param TContext The type of the context, which must extend [AIAgentContext]. This provides details about
 * the environment, state, configuration, and other metadata during the agent's lifecycle.
 *
 * @property output The result output produced by the AI agent after processing.
 * @property context The contextual information associated with the AI agent's execution.
 */
public data class AIAgentContextualResult<TOutput, TContext : AIAgentContext>(
    override val output: TOutput,
    public val context: TContext,
) : AIAgentResult<TOutput>
