package ai.koog.agents.core.agent

/**
 * Represents the result produced by an AI agent after processing.
 * This interface provides a generic structure to encapsulate the output generated by the agent.
 *
 * @param TOutput The type of the output produced by the AI agent.
 */
public interface AIAgentResult<TOutput> {

    /**
     * The output produced by the AI agent after processing.
     * Represents the result encapsulated in the generic structure of the AIAgentResult.
     */
    public val output: TOutput
}
