package ai.koog.agents.core.agent

import ai.koog.agents.core.agent.GraphAIAgent.FeatureContext
import ai.koog.agents.core.agent.config.AIAgentConfig
import ai.koog.agents.core.agent.entity.AIAgentGraphStrategy
import ai.koog.agents.core.annotation.InternalAgentsApi
import ai.koog.agents.core.tools.ToolRegistry
import ai.koog.prompt.dsl.prompt
import ai.koog.prompt.executor.model.PromptExecutor
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.llm.OllamaModels
import ai.koog.prompt.params.LLMParams
import io.ktor.util.collections.ConcurrentMap
import kotlinx.datetime.Clock
import kotlin.reflect.KType
import kotlin.reflect.typeOf

/**
 * [AIAgentService] is a core interface for managing AI agents. The service allows creation, removal, and
 * management of AI agents and provides functionalities to list agents based on their statuses.f
 *
 * A single instance of [AIAgentService] manages one kind of uniform AI Agents serving same purpose and solving same type
 * of user task. It's useful to create, manage, and track progress of running agents solving similar user tasks in parallel.
 *
 * @param Input Type parameter for the input data for the agents.
 * @param Output Type parameter for the output data generated by the agents.
 */
public interface AIAgentService<Input, Output> {

    /**
     * Represents an instance of PromptExecutor responsible for executing prompt-based operations.
     *
     * This variable is utilized to handle interactions and executions related to prompts,
     * providing a centralized mechanism to manage user inputs or automated instructions.
     */
    public val promptExecutor: PromptExecutor

    /**
     * Holds the configuration details for an AI agent.
     *
     * This property encapsulates the settings and parameters
     * required to initialize and operate an AI agent, such as
     * behavior configurations, thresholds, or any specific operational
     * constraints. It is essential for defining the agent's behavior and performance.
     */
    public val agentConfig: AIAgentConfig

    /**
     * Represents the central repository or registry for managing tools within the system.
     *
     * This variable provides access to a tool registry that can be used to store, retrieve,
     * and manage different tools registered in the application.
     *
     * It is expected to be immutable and thread-safe, ensuring consistent behavior across the application.
     */
    public val toolRegistry: ToolRegistry

    /**
     * Companion object that provides factory methods for creating instances of
     * GraphAIAgentService with various configurations.
     */
    public companion object {
        /**
         * Invokes the creation of a `GraphAIAgentService` instance with the provided configuration, strategy,
         * tool registry, and optional feature installation logic.
         *
         * @param promptExecutor The executor responsible for processing AI prompts and responses.
         * @param agentConfig Configuration parameters for the AI agent.
         * @param strategy A strategy defining the graph structure for AI agent interactions and processing.
         * @param toolRegistry*/
        @OptIn(InternalAgentsApi::class)
        public inline operator fun <reified Input, reified Output> invoke(
            promptExecutor: PromptExecutor,
            agentConfig: AIAgentConfig,
            strategy: AIAgentGraphStrategy<Input, Output>,
            toolRegistry: ToolRegistry = ToolRegistry.EMPTY,
            noinline installFeatures: FeatureContext.() -> Unit = {},
        ): GraphAIAgentService<Input, Output> = GraphAIAgentService(
            promptExecutor = promptExecutor,
            agentConfig = agentConfig,
            strategy = strategy,
            inputType = typeOf<Input>(),
            outputType = typeOf<Output>(),
            toolRegistry = toolRegistry,
            installFeatures = installFeatures
        )

        /**
         * Invokes the creation of a `GraphAIAgentService` with the provided dependencies, configuration,
         * and optional parameters for customization.
         *
         * @param promptExecutor The executor responsible for handling prompt-based interactions.
         * @param llmModel The large language model to be used by the agent.
         * @param strategy The graph strategy defining the agent's execution behavior. Defaults to a single-run*/
        public operator fun invoke(
            promptExecutor: PromptExecutor,
            llmModel: LLModel,
            strategy: AIAgentGraphStrategy<String, String> = singleRunStrategy(),
            toolRegistry: ToolRegistry = ToolRegistry.EMPTY,
            id: String? = null,
            systemPrompt: String = "",
            temperature: Double = 1.0,
            numberOfChoices: Int = 1,
            maxIterations: Int = 50,
            installFeatures: FeatureContext.() -> Unit = {}
        ): GraphAIAgentService<String, String> = AIAgentService(
            promptExecutor = promptExecutor,
            strategy = strategy,
            agentConfig = AIAgentConfig(
                prompt = prompt(
                    id = "chat",
                    params = LLMParams(
                        temperature = temperature,
                        numberOfChoices = numberOfChoices
                    )
                ) {
                    system(systemPrompt)
                },
                model = llmModel,
                maxAgentIterations = maxIterations,
            ),
            toolRegistry = toolRegistry,
            installFeatures = installFeatures
        )
    }

    /**
     * Creates a new instance of an AI agent with the specified parameters.
     *
     * @param id An optional unique identifier for the agent. If null, a default identifier will be generated.
     * @param clock The clock instance used to manage time-related operations. Defaults to the system clock.
     * @return A new instance of an AI agent configured with the provided parameters.
     */
    public fun createAgent(
        id: String? = null,
        clock: Clock = Clock.System
    ): AIAgent<Input, Output>

    /**
     * Creates a new AI agent with the specified optional parameters ([id], [clock]), executes it with the given input,
     * and retrieves the resulting output.
     *
     * @param agentInput The input to be processed by the AI agent.
     * @param id An optional unique identifier for the agent. If null, a default identifier will be generated.
     * @param clock The clock instance used to manage time-related operations. Defaults to the system clock.
     * @return The output produced by the agent after processing the input.
     */
    public suspend fun createAgentAndRun(
        agentInput: Input,
        id: String? = null,
        clock: Clock = Clock.System
    ): Output = createAgent(id, clock).run(agentInput)

    /**
     * Removes the specified AI agent from the service.
     *
     * @param agent The AI agent to be removed.
     * @return True if the agent was successfully removed, or false if the agent was not found.
     */
    public fun removeAgent(agent: AIAgent<Input, Output>): Boolean

    /**
     * Removes an AI agent from the service by its unique identifier.
     *
     * @param id The unique identifier of the AI agent to be removed.
     * @return True if the agent was successfully removed, or false if no agent with the given identifier was found.
     */
    public fun removeAgentById(id: String): Boolean

    /**
     * Retrieves an AI agent from the service by its unique identifier.
     *
     * @param id The unique identifier of the AI agent to retrieve.
     * @return The AI agent with the specified identifier, or null if no agent with the given identifier is found.
     */
    public fun agentById(id: String): AIAgent<Input, Output>?

    /**
     * Retrieves a comprehensive list of all AI agents currently managed by the service,
     * regardless of their state (active, inactive, or finished).
     *
     * @return A list of all AI agents managed by the service.
     */
    public suspend fun listAllAgents(): List<AIAgent<Input, Output>>

    /**
     * Retrieves a list of active AI agents currently managed by the service.
     *
     * @return A list containing the currently active AI agents.
     */
    public suspend fun listActiveAgents(): List<AIAgent<Input, Output>>

    /**
     * Retrieves a list of inactive AI agents currently managed by the service.
     *
     * @return A list of AI agents that are marked as inactive.
     */
    public suspend fun listInactiveAgents(): List<AIAgent<Input, Output>>

    /**
     * Retrieves a list of AI agents that have completed their tasks and are marked as finished.
     *
     * @return A list of finished AI agents.
     */
    public suspend fun listFinishedAgents(): List<AIAgent<Input, Output>>

    /**
     * Closes all AI agents currently managed by the service.
     *
     * This method retrieves the list of all agents, regardless of their state (active, inactive, or finished),
     * and invokes the [AIAgent.close] function on each of them, releasing any underlying resources.
     */
    public suspend fun closeAll() {
        listAllAgents().forEach { it.close() }
    }
}

/**
 * Abstract base class for implementing an AI Agent Service. This class provides
 * foundational functionality for managing and interacting with AI agents.
 *
 * The class maintains a list of AI agents under its management and defines
 * common operations, such as creation, removal, querying, and shutting down agents.
 * Concrete implementations are expected to define the behavior for creating managed agents.
 *
 * @param Input the input type expected by the AI agents.
 * @param Output the output type expected from the AI agents.
 */
public abstract class AIAgentServiceBase<Input, Output> : AIAgentService<Input, Output> {
    /**
     * A mutable list that holds the agents currently managed by the AIAgentServiceBase instance.
     *
     * This list is used to track all agents created and managed by the service, allowing for operations
     * such as addition, removal, and querying of agents based on their state or lifecycle.
     */
    protected val managedAgents: ConcurrentMap<String, AIAgent<Input, Output>> = ConcurrentMap()

    /**
     * Creates and registers a managed AI agent with an optional identifier and clock instance.
     *
     * @param id An optional identifier for the managed agent. If not provided, a unique identifier may be generated internally.
     * @param clock A clock instance used for time-related operations within the agent. Defaults to the system clock.
     * @return The newly created AI agent instance of type AIAgent<Input, Output>.
     */
    @InternalAgentsApi
    public abstract fun createManagedAgent(
        id: String? = null,
        clock: Clock = Clock.System
    ): AIAgent<Input, Output>

    /**
     * Creates and registers a new AI agent using the provided agent ID and clock.
     *
     * @param id Optional identifier for the AI agent. If null, a default ID will be generated.
     * @param clock A clock instance to manage time-related operations for the agent.
     * @return AIAgent instance with the specified configurations.
     */
    @OptIn(InternalAgentsApi::class)
    final override fun createAgent(id: String?, clock: Clock): AIAgent<Input, Output> {
        val agent = createManagedAgent(id, clock)
        managedAgents[agent.id] = agent
        return agent
    }

    /**
     * Removes the specified AI agent from the managed agents list.
     *
     * @param agent The AI agent to be removed.
     * @return `true` if the specified agent was successfully removed, otherwise `false`.
     */
    final override fun removeAgent(agent: AIAgent<Input, Output>): Boolean = removeAgentById(agent.id)

    /**
     * Removes the AI agent identified by the given ID from the managed agents list.
     *
     * @param id The unique identifier of the AI agent to be removed.
     * @return `true` if an agent with the specified ID was successfully removed, otherwise `false`.
     */
    final override fun removeAgentById(id: String): Boolean = managedAgents.remove(id) != null

    /**
     * Retrieves an AI agent managed by this service based on the provided unique identifier.
     *
     * @param id The unique identifier of the AI agent to be retrieved.
     * @return The AI agent corresponding to the given identifier, or `null` if no agent with the specified ID exists.
     */
    final override fun agentById(id: String): AIAgent<Input, Output>? = managedAgents[id]

    /**
     * Retrieves a list of all currently active AI agents managed by the service.
     *
     *
     * @return A list of active AI agents of type `AIAgent<Input, Output>`.
     */
    final override suspend fun listActiveAgents(): List<AIAgent<Input, Output>> =
        managedAgents.filterValues { it.isRunning() }.values.toList()

    /**
     * Retrieves a list of inactive AI agents managed by this service.
     *
     * An agent is considered inactive if it is not currently running.
     *
     * @return A list of AI agents that are inactive.
     */
    final override suspend fun listInactiveAgents(): List<AIAgent<Input, Output>> =
        managedAgents.filterValues { !it.isRunning() }.values.toList()

    /**
     * Retrieves a list of all agents that have already finished their task.
     *
     * @return A list of finished agents managed by this service.
     */
    final override suspend fun listFinishedAgents(): List<AIAgent<Input, Output>> =
        managedAgents.filterValues { it.finished() }.values.toList()

    /**
     * Retrieves a list of all AI agents currently managed by the service, regardless of their state
     * (e.g., active, inactive, or finished).
     *
     * @return A list of all AI agents of type `AIAgent<Input, Output>` managed by this service.
     */
    override suspend fun listAllAgents(): List<AIAgent<Input, Output>> = managedAgents.values.toList()
}

/**
 * A service class for managing graph-based AI agents, responsible for orchestrating the behavior
 * and execution of agents within a configurable graph-based strategy.
 *
 * This class extends [AIAgentServiceBase] and provides an implementation for creating
 * AI agents that follow a graph-based approach. It leverages a strategy pattern
 * defined by [AIAgentGraphStrategy] to handle input and output transformations.
 *
 * The [GraphAIAgentService] is marked with the [InternalAgentsApi] annotation,
 * indicating that it is intended for internal use within agent-related implementations and not
 * guaranteed for backward compatibility.
 *
 * @param promptExecutor An instance of [PromptExecutor], responsible for executing prompts
 *        using language models and handling responses.
 **/
@Suppress("MissingKDocForPublicAPI")
public class GraphAIAgentService<Input, Output>
@InternalAgentsApi
public constructor(
    override val promptExecutor: PromptExecutor,
    override val agentConfig: AIAgentConfig,
    public val strategy: AIAgentGraphStrategy<Input, Output>,
    private val inputType: KType,
    private val outputType: KType,
    override val toolRegistry: ToolRegistry,
    public val installFeatures: FeatureContext.() -> Unit
) : AIAgentServiceBase<Input, Output>() {

    /**
     * Creates a managed AI agent with the specified identifier and clock.
     *
     * @param id The optional unique identifier for the created agent. If null, a default identifier may be used.
     * @param clock The clock instance used for time-related operations within the agent.
     * @return A managed AI agent instance implementing the AIAgent interface.
     */
    @InternalAgentsApi
    override fun createManagedAgent(
        id: String?,
        clock: Clock
    ): AIAgent<Input, Output> = GraphAIAgent(
        inputType = inputType,
        outputType = outputType,
        promptExecutor = promptExecutor,
        agentConfig = agentConfig,
        toolRegistry = toolRegistry,
        strategy = strategy,
        id = id,
        clock = clock,
        installFeatures = installFeatures
    )
}

/**
 * A service for managing functional AI agents that operate based on a specified execution strategy.
 *
 * This class provides the infrastructure for creating and managing functional AI agents.
 * It integrates an execution strategy with associated input and output types, a tool registry for
 * additional functionalities, and a customizable feature installation context.
 *
 * @param Input The type of input data that the functional AI agent will process.
 * @param Output The type of output data produced by the functional AI agent.
 * @property promptExecutor The executor responsible for handling and executing prompts.
 * @property agentConfig The configuration settings for the AI agent, including model and prompt behavior.
 * @property strategy The functional strategy defining the agent's iteration logic and processing behavior.
 * @property inputType The Kotlin type information corresponding*/
@Suppress("MissingKDocForPublicAPI")
public class FunctionalAIAgentService<Input, Output>
@InternalAgentsApi
public constructor(
    override val promptExecutor: PromptExecutor,
    override val agentConfig: AIAgentConfig,
    public val strategy: AIAgentFunctionalStrategy<Input, Output>,
    private val inputType: KType,
    private val outputType: KType,
    override val toolRegistry: ToolRegistry,
    public val installFeatures: FunctionalAIAgent.FeatureContext.() -> Unit
) : AIAgentServiceBase<Input, Output>() {

    /**
     * Creates and returns a managed instance of [FunctionalAIAgent].
     *
     * @param id The unique identifier for the agent instance. If null, a new identifier is generated.
     * @param clock The clock instance used for time-related operations within the agent.
     * @return A [FunctionalAIAgent] instance configured with the associated properties and dependencies.
     */
    @InternalAgentsApi
    override fun createManagedAgent(
        id: String?,
        clock: Clock
    ): FunctionalAIAgent<Input, Output> = FunctionalAIAgent(
        promptExecutor = promptExecutor,
        agentConfig = agentConfig,
        toolRegistry = toolRegistry,
        strategy = strategy,
        id = id,
        clock = clock,
        featureContext = installFeatures
    )
}

private suspend fun f(executor: PromptExecutor) {
    val Service = AIAgentService(
        executor,
        OllamaModels.Meta.LLAMA_3_2,
        toolRegistry = ToolRegistry {}
    )

    val agent = Service.createAgent()

    val result = agent.run("Hi")
}

/**
 * Invokes the process to create and return an instance of `GraphAIAgentService`.
 *
 * @param promptExecutor The executor responsible for handling prompts during the agent's operation.
 * @param agentConfig The configuration object for the AI agent.
 * @param strategy The strategy defining how the agent processes tasks and connections within the graph. Defaults to `singleRunStrategy`.
 * @param toolRegistry The registry containing tools available for the agent to use. Defaults to an empty*/
@OptIn(InternalAgentsApi::class)
public operator fun AIAgentService.Companion.invoke(
    promptExecutor: PromptExecutor,
    agentConfig: AIAgentConfig,
    strategy: AIAgentGraphStrategy<String, String> = singleRunStrategy(),
    toolRegistry: ToolRegistry = ToolRegistry.EMPTY,
    installFeatures: FeatureContext.() -> Unit = {},
): GraphAIAgentService<String, String> = GraphAIAgentService(
    promptExecutor = promptExecutor,
    agentConfig = agentConfig,
    strategy = strategy,
    inputType = typeOf<String>(),
    outputType = typeOf<String>(),
    toolRegistry = toolRegistry,
    installFeatures = installFeatures
)
