package ai.koog.agents.core.agent

import ai.koog.agents.core.agent.context.AIAgentContext
import ai.koog.agents.core.agent.context.element.AgentRunInfoContextElement
import ai.koog.agents.core.agent.entity.AIAgentGraphStrategy
import ai.koog.agents.core.agent.entity.AIAgentStrategy
import ai.koog.agents.core.feature.AIAgentPipeline
import io.github.oshai.kotlinlogging.KLogger
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import kotlin.reflect.KType
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Abstract base class representing a single-use AI agent with state.
 *
 * This AI agent is designed to execute a specific long-running strategy only once, and provides API to monitor and manage it's state.
 *
 * It maintains internal states including its running status, whether it was started, its result (if available), and
 * the root context associated with its execution. The class enforces safe state transitions and provides
 * thread-safe operations via a mutex.
 *
 * @param Input the type of the input accepted by the agent.
 * @param Output the type of the output produced by the agent.
 * @param TContext the type of the context used during the agent's execution, extending [AIAgentContext].
 * @property strategy the execution strategy defining how the agent processes input and produces output.
 * @property logger the logger used for logging execution details and errors.
 * @property id unique identifier for the agent instance, autogenerated if not provided during instantiation.
 */
@OptIn(ExperimentalUuidApi::class)
public abstract class StatefulSingleUseAIAgent<Input, Output, TContext : AIAgentContext>(
    public val strategy: AIAgentStrategy<Input, Output, TContext>,
    private val logger: KLogger,
    agentId: String? = null
) : AIAgent<Input, Output> {
    /**
     * Indicates whether the agent is currently running.
     *
     * This variable is used to track the running state of the agent. It is mutable and
     * can be updated to reflect the current operational status of the agent. It is set
     * to `false` by default, meaning the agent is not running.
     */
    protected var isRunning: Boolean = false

    /**
     * Indicates whether the agent has been started.
     *
     * This variable is used to track if the agent's execution process has begun.
     * It is primarily utilized internally to ensure that methods or operations
     * depending on the agent's startup state react appropriately.
     *
     * By default, this variable is initialized to `false`, representing that the agent
     * has not yet started.
     */
    protected var wasStarted: Boolean = false

    /**
     * Represents the result or output of an agent's operation.
     * This variable is of a nullable type and may hold the result of a computation or remain null if no result is produced.
     * It is protected, meaning it is accessible within the class and by subclasses.
     */
    protected var agentResult: Output? = null

    /**
     * The root context associated with the agent during its lifecycle. This context is expected to be defined
     * during the preparation phase and is used for managing the agent's execution state and interactions.
     *
     * It is nullable to indicate that the context may not be available before initialization or after
     * the agent's lifecycle ends.
     */
    protected var rootAgentContext: TContext? = null

    /**
     * A mutex used to synchronize access to the state of the agent. Ensures that only one coroutine
     * can modify or read the shared state of the agent at a time, preventing data races and ensuring
     * thread-safe operations.
     */
    protected val agentStateMutex: Mutex = Mutex()

    /**
     * A unique identifier represented as a string. This identifier is lazily initialized.
     * If a value is present in `agentId`, it will use that; otherwise, it will generate
     * a random UUID string.
     */
    final override val id: String by lazy { agentId ?: Uuid.random().toString() }

    /**
     * Determines whether the agent is currently in a running state.
     *
     * @return `true` if the agent is running, `false` otherwise.
     */
    final override suspend fun isRunning(): Boolean = agentStateMutex.withLock {
        isRunning
    }

    /**
     * Determines if the process or operation has completed its execution.
     *
     * This method evaluates the state of the associated process, ensuring it was started
     * and is no longer running.
     *
     * @return `true` if the operation was started and is no longer running, otherwise `false`.
     */
    final override suspend fun finished(): Boolean = agentStateMutex.withLock {
        wasStarted && !isRunning
    }

    /**
     * Retrieves the result of the agent if it is in a finished state, or returns null if it is not ready yet.
     *
     * The method ensures thread-safety by using a locking mechanism to access the agent's state.
     *
     * @return The calculated result of type [Output] if the agent has finished execution, or null if it is not ready.
     */
    final override suspend fun resultIfReady(): Output? =
        agentStateMutex.withLock { if (finished()) agentResult else null }


    /**
     * Represents the pipeline used by the AI agent for processing tasks or data.
     *
     * This abstract property defines the structure or sequence of operations
     * within the AI agent's pipeline. It serves as the core mechanism for
     * executing workflows, handling inputs, and generating outputs in the
     * AI agent's functionality.
     */
    public abstract val pipeline: AIAgentPipeline

    /**
     * Executes the agent's main functionality, coordinating with various components
     * such as pipelines and strategies. Ensures the agent is run in a thread-safe
     * manner using locking mechanisms.
     *
     * @param agentInput The input required to execute the agent's strategy.
     *                   This includes any data necessary for processing.
     * @return The output generated by the agent's execution, produced as a
     *         result of applying the strategy to the provided input.
     * @throws IllegalStateException if the agent was already started.
     * @throws Throwable if any exception occurs during the execution process.
     */
    final override suspend fun run(agentInput: Input): Output {
        agentStateMutex.withLock {
            if (wasStarted) {
                throw IllegalStateException("Agent was already started")
            }
            isRunning = true
            wasStarted = true
        }

        val runId = Uuid.random().toString()

        pipeline.prepareFeatures()

        return withContext(
            AgentRunInfoContextElement(
                agentId = this@StatefulSingleUseAIAgent.id,
                runId = runId,
                agentConfig = agentConfig,
                strategyName = strategy.name
            )
        ) {
            val context = prepareContext(agentInput, runId)
            agentStateMutex.withLock {
                rootAgentContext = context
            }

            logger.debug {
                formatLog(
                    agentId = this@StatefulSingleUseAIAgent.id,
                    runId = runId,
                    message = "Starting agent execution"
                )
            }

            pipeline.onAgentStarting<Input, Output>(
                runId = runId,
                agent = this@StatefulSingleUseAIAgent,
                context = rootAgentContext!!
            )

            val result = try {
                strategy.execute(context = rootAgentContext!!, input = agentInput)
            } catch (e: Throwable) {
                logger.error(e) { "Execution exception reported by server!" }
                pipeline.onAgentExecutionFailed(
                    agentId = this@StatefulSingleUseAIAgent.id,
                    runId = runId,
                    throwable = e
                )
                throw e
            } finally {
                agentStateMutex.withLock {
                    isRunning = false
                }
            }

            logger.debug {
                formatLog(
                    agentId = this@StatefulSingleUseAIAgent.id,
                    runId = runId,
                    message = "Finished agent execution"
                )
            }
            pipeline.onAgentCompleted(
                agentId = this@StatefulSingleUseAIAgent.id,
                runId = runId,
                result = result
            )

            agentStateMutex.withLock {
                agentResult = result
            }

            return@withContext result ?: error("result is null")
        }
    }

    /**
     * Executes a given action within the context of a running AI agent if the root context exists.
     *
     * @param action A suspend function to be executed within the AI agent's context. This lambda
     *               extension function operates on the current [AIAgentContext].
     * @return `true` if the action was successfully executed with a valid root context; `false` otherwise.
     */
    final override suspend fun withRunningContext(action: suspend AIAgentContext.() -> Unit): Boolean =
        agentStateMutex.withLock {
            rootAgentContext?.action()?.let { true } ?: false
        }

    /**
     * Closes the AI Agent and performs necessary cleanup operations.
     *
     * This method is a suspending function that ensures that the AI Agent's resources are released
     * when it is no longer needed. It notifies the pipeline of the agent's closure and ensures
     * that any associated features or stream providers are properly closed.
     *
     * Overrides the `close` method to implement agent-specific shutdown logic.
     */
    final override suspend fun close() {
        pipeline.onAgentClosing(agentId = this@StatefulSingleUseAIAgent.id)
        pipeline.closeFeaturesStreamProviders()
    }

    /**
     * Prepares and initializes the agent context required to handle the given input and run ID.
     *
     * @param agentInput the input provided to the agent for processing.
     * @param runId a unique identifier representing the current execution or operation run.
     * @return the initialized context specific to the agent setup for the provided input and run ID.
     */
    public abstract suspend fun prepareContext(agentInput: Input, runId: String): TContext

    /**
     * Formats a log message with the specified agent ID, run ID, and message content.
     *
     * @param agentId The unique identifier of the agent generating the log.
     * @param runId The unique identifier of the specific run or task associated with the log.
     * @param message The content of the log message to be formatted.
     * @return A formatted log string containing the agent ID, run ID, and the provided message.
     */
    protected fun formatLog(agentId: String, runId: String, message: String): String =
        "[agent id: $agentId, run id: $runId] $message"
}
