{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-core",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-metadata-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-generator-core-0.3.3-SNAPSHOT.jar",
          "size": 12477,
          "sha512": "44a44e4d096dc17ae77b313b19c07eb9859130540b9119bf3de68e5da9197f873962b5a5ca6e91a0728c66387f28458d2889342ef258b77b512ea235fb42e19c",
          "sha256": "63ec22ffc812ca386e56cb847355688dbcb9ba98ba11727f16d62175cf7e5120",
          "sha1": "a7098a271b46022280d090265c8ded35a08d854d",
          "md5": "0b090dae8c0bedb509e62c119ca23d05"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-core-kotlin-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-core-0.3.3-SNAPSHOT-sources.jar",
          "size": 12237,
          "sha512": "81480629c524b7c0b3a9d6aa858b608c6e501a4b975b7a968d3d8cf7c694db47dd0f68930c1dd1722a70b20a909393edb75eedad4289af69cb558511cecf6acf",
          "sha256": "e4723f637da6aab9a86e992a127ef3f4cb0566ddb184c876c1accdc74f7f9086",
          "sha1": "2ad65e405c32b2d783482b4ed3f62979eeeadbcf",
          "md5": "1b52bd6e7f4209dd9fc87f5b198f02cd"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-jvm/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-jvm/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-jvm/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-linuxarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-linuxarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-linuxarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-linuxarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-linuxarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-linuxarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-linuxx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-linuxx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-linuxx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-linuxx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-linuxx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-linuxx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-mingwx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-mingwx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-mingwx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-mingwx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-mingwx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-mingwx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-core-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-core-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    }
  ]
}
