{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-generator-core/0.3.3-SNAPSHOT/kotlinx-schema-generator-core-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-core",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-core-linuxX64Main-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-generator-core-linuxx64-0.3.3-SNAPSHOT.klib",
          "size": 39430,
          "sha512": "6fe78da4e3df3c79e907db5a4b683c28c02080403aa0fee9be2e6e799177a8cfa84d631c590111f782c715587541d42b321f0eadbd41e3e78c96120d680e093c",
          "sha256": "1e0bf6980ac55ba3318b62c5feb764ef34929115dd8fe47610fba072380f5218",
          "sha1": "0e19fb842d1fd07e7d5674eb78deed950e0489d9",
          "md5": "41706d41609334e32bb34473f016abfa"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-core-linuxx64-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-core-linuxx64-0.3.3-SNAPSHOT-sources.jar",
          "size": 11277,
          "sha512": "269bd266e0b42e6f92f4cb86d10f7b5f019b29bd8ffabdbb2a85f74b2c9c6520b13fbfd86f6818751f7569e8f40c6cfa49f6c009bf3c87609cddce545c829d3b",
          "sha256": "00baf7bbae0bbd1909617490c5cb129498aca2827443e447ba80a6afaaf724d3",
          "sha1": "1e61f1361475152527619eabe3e16134a55e8d88",
          "md5": "08bcf0baca4ff5a0a07cf7a3c6c6da28"
        }
      ]
    }
  ]
}
