flowchart TD
    Start([nodeStart])
    Code[code]
    Test[test]
    Fix[fix]
    Finish([nodeFinish: Done!])

    Start --> Code
    Code --> Test
    Test -->|problems not empty| Fix
    Fix --> Test
    Test -->|problems empty| Finish
