package ai.koog.agents.testing.llm

import ai.koog.prompt.dsl.prompt
import ai.koog.prompt.executor.clients.LLMClient
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.params.LLMParams
import io.kotest.assertions.withClue
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldStartWith
import io.ktor.client.plugins.*
import io.ktor.http.*
import kotlinx.coroutines.test.TestResult
import kotlinx.coroutines.test.runTest
import me.kpavlov.aimocks.core.AbstractBuildingStep
import me.kpavlov.aimocks.core.AbstractMockLlm
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import org.junit.jupiter.api.assertThrows
import org.junit.jupiter.api.parallel.Execution
import org.junit.jupiter.api.parallel.ExecutionMode
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.Arguments.argumentSet
import org.junit.jupiter.params.provider.MethodSource
import kotlin.random.Random.Default.nextDouble
import kotlin.reflect.KClass
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds

private val TIMEOUT: Duration = 500.milliseconds

/**
 * Abstract test class for evaluating error handling capabilities of LLM clients.
 * This class is responsible for testing various error responses, timeouts,
 * and ensuring proper behavior of client implementations under error scenarios.
 *
 * @param LLM_CLIENT The type of the language model client being tested.
 * @param MOCK The type of the mock implementation to simulate the LLM client behavior.
 * @property mock The mock instance used to prepare and verify test scenarios.
 * @property model The language model used in tests for interaction with the client.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@Execution(ExecutionMode.CONCURRENT)
public abstract class AbstractLLMClientErrorsTest<out LLM_CLIENT : LLMClient, out MOCK : AbstractMockLlm>(
    protected val mock: MOCK,
    protected val model: LLModel,
) {

    /**
     * Creates an instance of a language model client with the specified configuration.
     *
     * @param temperature The temperature value defining the randomness or creativity of the responses generated by the client.
     * @param requestTimeout Optional custom request timeout duration for the client's operations.
     *  If null, a default timeout might be used.
     * @return A configured instance of an LLM_CLIENT.
     */
    protected abstract fun createClient(temperature: Double, requestTimeout: Duration? = null): LLM_CLIENT

    /**
     * Prepares a mock response to simulate the behavior of an LLM client for a specific question and temperature.
     *
     * @param question The input question or prompt for which the mock behavior is prepared.
     * @param temperature The temperature value defining the randomness or creativity of the response generation.
     * @return An abstract building step allowing further customization or configuration of the mock behavior.
     */
    protected abstract fun prepareMock(question: String, temperature: Double): AbstractBuildingStep<*, *>

    /**
     * Generates an error response body with the specified error message.
     *
     * @param message The error message to include in the response body.
     * @return A string representing the generated error response body.
     */
    protected open fun errorResponseBody(message: String): String = ""

    @AfterEach
    protected fun afterEach() {
        mock.verifyNoUnmatchedRequests()
    }

    @ParameterizedTest(name = "{argumentSetName}({0}) -> {1}")
    @MethodSource("errors")
    protected fun `Should handle error responses`(
        httpStatusCode: Int,
        expectedException: KClass<Exception>
    ): TestResult = runTest {
        // given
        val temperature = nextDouble(0.1, 1.0) // ⚠️ Must be unique per execution!

        val question = "Return error: $httpStatusCode"
        val message = "Error : $httpStatusCode"

        prepareMock(question = question, temperature = temperature)
            .respondsError(responseType = String::class) {
                httpStatus = HttpStatusCode.fromValue(httpStatusCode)
                body = errorResponseBody(message)
            }

        val client = createClient(temperature = temperature)

        val prompt = prompt(
            id = "error-$httpStatusCode",
            params = LLMParams(temperature = temperature)
        ) {
            user(question)
        }

        // when-then
        val exception = assertThrows<Exception> {
            client.execute(
                prompt = prompt,
                model = model,
            )
        }

        withClue("Exception `$exception` should be instance of $expectedException") {
            exception.javaClass shouldBe expectedException.java
        }
        exception.message shouldContain "$httpStatusCode"
    }

    @Test
    protected fun `Should handle request timeout`(): TestResult = runTest {
        // given
        val temperature = nextDouble(0.1, 1.0) // ⚠️ Must be unique per execution!

        val client = createClient(temperature, requestTimeout = TIMEOUT)

        val question = "Simulate timeout"

        prepareMock(question = question, temperature = temperature)
            .respondsError(responseType = String::class) {
                httpStatus = HttpStatusCode.OK
                delay = TIMEOUT * 2
                body = errorResponseBody("timeout")
            }

        val prompt = prompt(
            id = "timeout",
            params = LLMParams(temperature = temperature)
        ) {
            user(question)
        }

        // when-then
        val exception = assertThrows<HttpRequestTimeoutException> {
            client.execute(
                prompt = prompt,
                model = model,
            )
        }

        exception.message shouldStartWith "Request timeout has expired"
    }

    protected open fun errors(): List<Arguments> = listOf(
        argumentSet(
            "Bad request",
            400,
            IllegalStateException::class
        ),
        argumentSet(
            "Unauthenticated",
            401,
            IllegalStateException::class
        ),
        argumentSet(
            "Unauthorized",
            403,
            IllegalStateException::class
        ),
        argumentSet(
            "Not found",
            404,
            IllegalStateException::class
        ),
        argumentSet(
            "Request entity too large",
            413,
            IllegalStateException::class
        ),
        argumentSet(
            "Too many requests",
            429,
            IllegalStateException::class
        ),
        argumentSet(
            "Internal server error",
            500,
            IllegalStateException::class
        ),
        argumentSet(
            "Service unavailable",
            503,
            IllegalStateException::class
        )
    )
}
