package ai.koog.prompt.llm

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmOverloads

/**
 * Represents a Large Language Model (LLM) with a specific provider, identifier, and a set of capabilities.
 *
 * @property provider The provider of the LLM, such as Google, OpenAI, or Meta.
 * @property id A unique identifier for the LLM instance. This typically represents the specific model version or name.
 * @property capabilities A list of capabilities supported by the LLM, such as temperature adjustment, tools usage, or schema-based tasks. Defaults to null.
 * @property contextLength The context length of the LLM. This is the maximum number of tokens the LLM can process. Defaults to null.
 * @property maxOutputTokens The maximum number of tokens that can be generated by the provider for the LLM.
 */
@Serializable
public data class LLModel @JvmOverloads constructor(
    val provider: LLMProvider,
    val id: String,
    val capabilities: List<LLMCapability>? = null,
    val contextLength: Long? = null,
    val maxOutputTokens: Long? = null,
) {
    /**
     * Checks if the Large Language Model (LLM) supports a specific capability.
     *
     * @param capability The capability to check for, represented by an instance of [LLMCapability].
     * @return `true` if the LLM supports the given capability, otherwise `false`.
     */
    public fun supports(capability: LLMCapability): Boolean = capabilities?.contains(capability) ?: false
}

/**
 * Checks if the Large Language Model (LLM) supports a specific capability.
 * @param capability The capability to check for, represented by an instance of [LLMCapability].
 */
public fun LLModel.requireCapability(capability: LLMCapability): Unit =
    require(supports(capability)) {
        "Model $id does not support ${capability.id} capability."
    }

/**
 * Ensures that the provided [LLModel] is associated with the same [LLMProvider].
 * Throws an [IllegalArgumentException] if the providers do not match.
 *
 * @param llmProvider The [LLMProvider] to compare against the current [LLModel].
 */
public fun LLModel.requireMatchingProvider(llmProvider: LLMProvider) {
    require(this.provider == llmProvider) {
        "Model provider mismatch: ${this.id}.provider=${this.provider}, " +
            "${this::class.simpleName ?: "(LLMProviderAware)"}.llmProvider=$llmProvider"
    }
}
