package ai.koog.prompt.executor.clients.retrollmfit

import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.agents.core.tools.ToolParameterType
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.executor.clients.LLMClient
import ai.koog.prompt.llm.LLMProvider
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.ContentPart
import ai.koog.prompt.message.Message
import ai.koog.prompt.message.ResponseMetaInfo
import ai.koog.prompt.streaming.StreamFrame
import io.github.oshai.kotlinlogging.KotlinLogging
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.header
import io.ktor.client.request.parameter
import io.ktor.client.request.post
import io.ktor.client.request.preparePost
import io.ktor.client.request.setBody
import io.ktor.http.ContentType
import io.ktor.http.contentType
import io.ktor.utils.io.ByteReadChannel
import io.ktor.utils.io.readUTF8Line
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put
import kotlin.reflect.KParameter
import kotlin.reflect.KProperty1
import kotlin.reflect.jvm.javaField
import kotlin.time.Clock

private val logger = KotlinLogging.logger {}

/**
 * A generic [ai.koog.prompt.executor.clients.LLMClient] generated by [RetroLLMFit].
 *
 * Supports flat completion, structured chat, tool calling, and SSE streaming —
 * all driven by annotations on the Req / Res data classes.
 *
 * Do not instantiate directly — use [RetroLLMFit.create].
 */
public class RetroLLMFitClient<Req : Any, Res : Any> @PublishedApi internal constructor(
    private val endpointUrl: String,
    private val authHeader: Pair<String, String>?,
    private val authQueryParam: Pair<String, String>?,
    internal val reqMeta: RequestMeta<Req>,
    internal val resMeta: ResponseMeta<Res>,
    private val requestSerializer: KSerializer<Req>,
    private val responseSerializer: KSerializer<Res>,
    private val httpClient: HttpClient,
    private val clock: Clock = Clock.System,
) : LLMClient() {

    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }

    override fun llmProvider(): LLMProvider = RetroLLMFitProvider

    override suspend fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>,
    ): List<Message.Response> {
        val request = reqMeta.build(prompt, model, tools, streaming = false)
        val responseText = post(json.encodeToString(requestSerializer, request), model)
        val response = json.decodeFromString(responseSerializer, responseText)
        return resMeta.parseResponse(response, responseSerializer, json, ResponseMetaInfo.create(clock))
    }

    override fun executeStreaming(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>,
    ): Flow<StreamFrame> = flow {
        requireNotNull(resMeta.streamDeltaPath) {
            "RetroLLMFit: streaming requested but response class has no @ResponseStreamDelta. " +
                "Add @ResponseStreamDelta(\"choices[0].delta.content\") to the response class."
        }

        val body = json.encodeToString(requestSerializer, reqMeta.build(prompt, model, tools, streaming = true))
        logger.debug { "RetroLLMFit SSE POST ${resolveUrl(model)}" }

        // SSE via raw ByteReadChannel — no ktor-client-sse plugin needed
        httpClient.preparePost(resolveUrl(model)) {
            contentType(ContentType.Application.Json)
            authHeader?.let { (n, v) -> header(n, v) }
            authQueryParam?.let { (n, v) -> parameter(n, v) }
            setBody(body)
        }.execute { response ->
            val channel: ByteReadChannel = response.body()
            while (!channel.isClosedForRead) {
                val line = channel.readUTF8Line() ?: break
                if (!line.startsWith("data:")) continue
                val data = line.removePrefix("data:").trim()
                if (data == "[DONE]") break
                runCatching {
                    val el = json.parseToJsonElement(data)
                    val delta = resolvePath(el, resMeta.streamDeltaPath)
                    if (delta != null && delta !is JsonNull) {
                        emit(StreamFrame.TextDelta(delta.jsonPrimitive.content))
                    }
                }
            }
        }
        emit(StreamFrame.End())
    }

    override suspend fun moderate(prompt: Prompt, model: LLModel): ModerationResult =
        ModerationResult(isHarmful = false, categories = emptyMap())

    override fun close(): Unit = httpClient.close()

    // Replaces {model} placeholder in URL with the actual model id.
    private fun resolveUrl(model: LLModel): String = endpointUrl.replace("{model}", model.id)

    private suspend fun post(body: String, model: LLModel): String {
        logger.debug { "RetroLLMFit POST ${resolveUrl(model)}" }
        return httpClient.post(resolveUrl(model)) {
            contentType(ContentType.Application.Json)
            authHeader?.let { (n, v) -> header(n, v) }
            authQueryParam?.let { (n, v) -> parameter(n, v) }
            setBody(body)
        }.body()
    }
}

// ─── RequestMeta ─────────────────────────────────────────────────────────────

@PublishedApi
internal class RequestMeta<Req : Any>(
    private val ctor: kotlin.reflect.KFunction<Req>,
    private val params: List<Pair<KParameter, ParamKind>>,
) {
    internal fun build(prompt: Prompt, model: LLModel, tools: List<ToolDescriptor>, streaming: Boolean): Req =
        ctor.callBy(params.associate { (param, kind) ->
            param to when (kind) {
                is ParamKind.PromptFlat -> flattenPrompt(prompt)
                is ParamKind.Messages   -> kind.serializer.serialize(prompt.messages)
                is ParamKind.Model      -> model.id
                is ParamKind.Tools      -> tools.takeIf { it.isNotEmpty() }?.let { buildTools(it, kind.format) }
                is ParamKind.Stream     -> streaming
            }
        })
}

internal sealed interface ParamKind {
    data object PromptFlat : ParamKind
    data class Messages(val serializer: MessagesSerializer) : ParamKind
    data object Model : ParamKind
    data class Tools(val format: ToolFormat) : ParamKind
    data object Stream : ParamKind
}

// ─── ResponseMeta ─────────────────────────────────────────────────────────────

@PublishedApi
internal class ResponseMeta<Res : Any>(
    private val textProperty: KProperty1<Res, *>?,
    val textPath: String?,
    val finishReasonPath: String?,
    val finishReasonToolCallValue: String,
    val toolCallsPath: String?,
    val toolCallsFormat: ToolFormat,
    val streamDeltaPath: String?,
) {
    fun parseResponse(
        res: Res,
        serializer: KSerializer<Res>,
        json: Json,
        metaInfo: ResponseMetaInfo,
    ): List<Message.Response> {
        val rawJson: JsonElement? = if (textPath != null || finishReasonPath != null || toolCallsPath != null) {
            json.encodeToJsonElement(serializer, res)
        } else null

        // Tool-call branch
        if (rawJson != null && finishReasonPath != null && toolCallsPath != null) {
            val finish = resolvePath(rawJson, finishReasonPath)?.jsonPrimitive?.content
            if (finish == finishReasonToolCallValue) {
                val arr = resolvePath(rawJson, toolCallsPath) as? JsonArray ?: return emptyList()
                return arr.mapNotNull { parseToolCall(it, metaInfo) }
            }
        }

        // Text branch
        val text = if (rawJson != null && textPath != null) {
            resolvePath(rawJson, textPath)?.let {
                if (it is JsonNull) null else it.jsonPrimitive.content
            } ?: ""
        } else {
            @Suppress("UNCHECKED_CAST")
            (textProperty?.getter?.call(res) as? String) ?: ""
        }

        return listOf(Message.Assistant(content = text, metaInfo = metaInfo))
    }

    private fun parseToolCall(el: JsonElement, metaInfo: ResponseMetaInfo): Message.Tool.Call? = when (toolCallsFormat) {
        ToolFormat.OPENAI -> {
            val obj = el.jsonObject
            val fn = obj["function"]?.jsonObject ?: return null
            Message.Tool.Call(
                id = obj["id"]?.jsonPrimitive?.content,
                tool = fn["name"]?.jsonPrimitive?.content ?: return null,
                content = fn["arguments"]?.jsonPrimitive?.content ?: "{}",
                metaInfo = metaInfo,
            )
        }
        ToolFormat.ANTHROPIC -> {
            val obj = el.jsonObject
            Message.Tool.Call(
                id = obj["id"]?.jsonPrimitive?.content,
                tool = obj["name"]?.jsonPrimitive?.content ?: return null,
                content = obj["input"]?.toString() ?: "{}",
                metaInfo = metaInfo,
            )
        }
    }
}

// ─── JSON path ────────────────────────────────────────────────────────────────

internal fun resolvePath(el: JsonElement, path: String): JsonElement? {
    var cur: JsonElement = el
    for (seg in path.split(".")) {
        val m = Regex("""^(.+)\[(\d+)]$""").matchEntire(seg)
        cur = if (m != null) {
            val (key, idx) = m.destructured
            ((cur as? JsonObject)?.get(key) as? JsonArray)?.getOrNull(idx.toInt()) ?: return null
        } else {
            (cur as? JsonObject)?.get(seg) ?: return null
        }
    }
    return cur
}

// ─── Tool serialization ───────────────────────────────────────────────────────

internal fun buildTools(tools: List<ToolDescriptor>, format: ToolFormat): List<JsonObject> =
    tools.map { it.toJson(format) }

private fun ToolDescriptor.toJson(format: ToolFormat): JsonObject = when (format) {
    ToolFormat.OPENAI -> buildJsonObject {
        put("type", "function")
        put("function", buildJsonObject {
            put("name", name)
            put("description", description)
            put("parameters", buildParamSchema())
        })
    }
    ToolFormat.ANTHROPIC -> buildJsonObject {
        put("name", name)
        put("description", description)
        put("input_schema", buildParamSchema())
    }
}

private fun ToolDescriptor.buildParamSchema(): JsonObject = buildJsonObject {
    put("type", "object")
    put("properties", buildJsonObject {
        (requiredParameters + optionalParameters).forEach { put(it.name, it.type.toSchema()) }
    })
    if (requiredParameters.isNotEmpty())
        put("required", buildJsonArray { requiredParameters.forEach { add(JsonPrimitive(it.name)) } })
}

private fun ToolParameterType.toSchema(): JsonObject = buildJsonObject {
    when (this@toSchema) {
        is ToolParameterType.String  -> put("type", "string")
        is ToolParameterType.Integer -> put("type", "integer")
        is ToolParameterType.Float   -> put("type", "number")
        is ToolParameterType.Boolean -> put("type", "boolean")
        is ToolParameterType.Null    -> put("type", "null")
        is ToolParameterType.Enum    -> { put("type", "string"); put("enum", buildJsonArray { entries.forEach { add(JsonPrimitive(it)) } }) }
        is ToolParameterType.List    -> { put("type", "array"); put("items", itemsType.toSchema()) }
        is ToolParameterType.Object  -> {
            put("type", "object")
            put("properties", buildJsonObject { properties.forEach { put(it.name, it.type.toSchema()) } })
            if (requiredProperties.isNotEmpty()) put("required", buildJsonArray { requiredProperties.forEach { add(JsonPrimitive(it)) } })
        }
        is ToolParameterType.AnyOf -> put("anyOf", buildJsonArray { types.forEach { add(it.type.toSchema()) } })
    }
}

// ─── Flat prompt helper ───────────────────────────────────────────────────────

internal fun flattenPrompt(prompt: Prompt): String =
    prompt.messages.joinToString("\n") { msg ->
        when (msg) {
            is Message.System    -> "System: ${msg.content}"
            is Message.User      -> msg.parts.filterIsInstance<ContentPart.Text>()
                .joinToString("") { it.text }.ifBlank { msg.content }
            is Message.Assistant -> "Assistant: ${msg.content}"
            else -> ""
        }
    }.trim()

// ─── Annotation helpers used by factory ──────────────────────────────────────

internal fun KProperty1<*, *>.hasJvmAnnotation(cls: Class<out Annotation>): Boolean =
    javaField?.isAnnotationPresent(cls) == true

internal fun KParameter.hasAnnotationByClass(cls: Class<out Annotation>): Boolean =
    annotations.any { cls.isInstance(it) }
