package ai.koog.prompt.executor.clients.retrollmfit

import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.executor.clients.LLMClient
import ai.koog.prompt.llm.LLMProvider
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.ContentPart
import ai.koog.prompt.message.Message
import ai.koog.prompt.message.ResponseMetaInfo
import io.github.oshai.kotlinlogging.KotlinLogging
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.header
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.http.ContentType
import io.ktor.http.contentType
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlin.time.Clock

private val logger = KotlinLogging.logger {}

/**
 * A generic [LLMClient] generated by [RetroLLMFit].
 * Do not instantiate directly — use [RetroLLMFit.create] instead.
 */
public class RetroLLMFitClient<Req : Any, Res : Any> @PublishedApi internal constructor(
    private val endpointUrl: String,
    private val authHeader: Pair<String, String>?,
    private val buildRequest: (String) -> Req,
    private val extractText: (Res) -> String,
    private val requestSerializer: KSerializer<Req>,
    private val responseSerializer: KSerializer<Res>,
    private val httpClient: HttpClient,
    private val clock: Clock = Clock.System,
) : LLMClient() {

    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }

    override fun llmProvider(): LLMProvider = RetroLLMFitProvider

    override suspend fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor>,
    ): List<Message.Response> {
        val promptText = flattenPrompt(prompt)
        val request = buildRequest(promptText)
        val requestBody = json.encodeToString(requestSerializer, request)

        logger.debug { "RetroLLMFit POST $endpointUrl — prompt length=${promptText.length}" }

        val responseText = httpClient.post(endpointUrl) {
            contentType(ContentType.Application.Json)
            authHeader?.let { (name, value) -> header(name, value) }
            setBody(requestBody)
        }.body<String>()

        val response = json.decodeFromString(responseSerializer, responseText)
        return listOf(
            Message.Assistant(
                content = extractText(response),
                metaInfo = ResponseMetaInfo.create(clock),
            )
        )
    }

    override suspend fun moderate(prompt: Prompt, model: LLModel): ModerationResult =
        ModerationResult(isHarmful = false, categories = emptyMap())

    override fun close() {
        httpClient.close()
    }

    private fun flattenPrompt(prompt: Prompt): String =
        prompt.messages.joinToString("\n") { msg ->
            when (msg) {
                is Message.System -> "System: ${msg.content}"
                is Message.User -> msg.parts
                    .filterIsInstance<ContentPart.Text>()
                    .joinToString("") { it.text }
                    .let { if (it.isBlank()) msg.content else it }
                is Message.Assistant -> "Assistant: ${msg.content}"
                else -> ""
            }
        }.trim()
}
