{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-json",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-generator-core",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-json",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-json-metadata-0.3.3-SNAPSHOT.jar",
          "url": "kotlinx-schema-generator-json-0.3.3-SNAPSHOT.jar",
          "size": 9808,
          "sha512": "d1ced1b8aaa7c20858187b02e32c20c4cdcc0f76f8a3618f837c917098a11fae00b6a8629acc18d57aac6d26bfa488e1f37638ef6d75bbe5f808fdec31386057",
          "sha256": "21b4516f9cdf1ede0da506b266a6340281d8cf9873b408d171ef3ead6ae2eac6",
          "sha1": "b750e69ac57d6cd880820b613cd99f3175d9eca7",
          "md5": "f610f5581a1b6e526b2c19974a9ffccd"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-json-kotlin-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-json-0.3.3-SNAPSHOT-sources.jar",
          "size": 19683,
          "sha512": "357f1227fe71824ffa8d4b42af5ac67a5af520b00f851b819dbabe1cdfc478ecaa59f9d6552e5add4e6d908b14faae16521c27258b35d67dd418660a976d34c3",
          "sha256": "1460a400b213aed030f072bf7ce267907e9e7e7bf9768019da78afdeb7e4077d",
          "sha1": "d7fa5b158e8eb64cd53fc26056bdc53e14bc8ba3",
          "md5": "db04f032cfa18b9e8771b0091a9e3867"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-iosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-iosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-iosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-jvm/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-jvm/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-jvm/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-jvm-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-jvm",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-linuxarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-linuxarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-linuxarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-linuxarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-linuxarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-linuxarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-linuxx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-linuxx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-linuxx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-linuxx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-linuxx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-linuxx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-macosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-macosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-macosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-macosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-macosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-macosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-mingwx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-mingwx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-mingwx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-mingwx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-mingwx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-mingwx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-tvosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-tvosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-tvosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-wasm-js/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-wasm-js-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-wasm-js",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosarm32/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosarm32-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosarm32",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchossimulatorarm64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchossimulatorarm64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchossimulatorarm64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-schema-generator-json-watchosx64/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-watchosx64-0.3.3-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-schema-generator-json-watchosx64",
        "version": "0.3.3-SNAPSHOT"
      }
    }
  ]
}
