@file:Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
@file:OptIn(InternalPromptAPI::class)

package ai.koog.prompt.executor.selection

import ai.koog.agents.annotations.JavaAPI
import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.annotations.InternalPromptAPI
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.execution.utils.runOnIOBoundDispatcher
import ai.koog.prompt.executor.model.PromptExecutor
import ai.koog.prompt.message.LLMChoice
import ai.koog.prompt.message.Message
import ai.koog.prompt.streaming.StreamFrame
import kotlinx.coroutines.jdk9.asPublisher
import java.util.concurrent.ExecutorService
import java.util.concurrent.Flow.Publisher

public actual abstract class SelectingPromptExecutor actual constructor() :
    PromptExecutor(), SelectingPromptExecutorAPI {

    /**
     * Blocking variant of [execute] for Java callers.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @param executorService Optional executor for running the coroutine. Uses the default IO dispatcher when `null`.
     * @return Responses generated by the selected model.
     */
    @JavaAPI
    @JvmOverloads
    public fun execute(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
        executorService: ExecutorService? = null
    ): List<Message.Response> = runOnIOBoundDispatcher(executorService) {
        execute(prompt, modelSelector, tools)
    }

    /**
     * Returns a [Publisher] that streams output frames for [prompt] using [modelSelector].
     *
     * Intended for Java callers that consume reactive streams. Kotlin callers should use
     * the [executeStreaming] extension instead.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @return [Publisher] emitting output frames from the selected model.
     */
    @JavaAPI
    @JvmOverloads
    public fun executeStreamingWithPublisher(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
    ): Publisher<StreamFrame> = executeStreaming(prompt, modelSelector, tools).asPublisher()

    /**
     * Blocking variant of [executeMultipleChoices] for Java callers.
     *
     * @param prompt Prompt containing messages and generation parameters.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param tools Tools available during execution.
     * @param executorService Optional executor for running the coroutine. Uses the default IO dispatcher when `null`.
     * @return Generated model choices.
     */
    @JavaAPI
    @JvmOverloads
    public fun executeMultipleChoices(
        prompt: Prompt,
        modelSelector: ModelSelector,
        tools: List<ToolDescriptor> = emptyList(),
        executorService: ExecutorService? = null
    ): List<LLMChoice> = runOnIOBoundDispatcher(executorService) {
        executeMultipleChoices(prompt, modelSelector, tools)
    }

    /**
     * Blocking variant of [moderate] for Java callers.
     *
     * @param prompt Prompt containing content to moderate.
     * @param modelSelector Selector that ranks models available to this executor.
     * @param executorService Optional executor for running the coroutine. Uses the default IO dispatcher when `null`.
     * @return Moderation result.
     */
    @JavaAPI
    @JvmOverloads
    public fun moderate(
        prompt: Prompt,
        modelSelector: ModelSelector,
        executorService: ExecutorService? = null
    ): ModerationResult = runOnIOBoundDispatcher(executorService) {
        moderate(prompt, modelSelector)
    }
}
