@file:Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
@file:OptIn(InternalPromptAPI::class)

package ai.koog.prompt.executor.model

import ai.koog.agents.annotations.JavaAPI
import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.annotations.InternalPromptAPI
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.execution.utils.runOnIOBoundDispatcher
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.LLMChoice
import ai.koog.prompt.message.Message
import ai.koog.prompt.streaming.StreamFrame
import kotlinx.coroutines.jdk9.asPublisher
import java.util.concurrent.ExecutorService
import java.util.concurrent.Flow.Publisher

@Suppress("MissingKDocForPublicAPI")
public actual abstract class PromptExecutor actual constructor() : PromptExecutorAPI {
    /**
     * Executes a given prompt using the specified LLM and tools, returning a list of responses from the model.
     *
     * @param prompt The `Prompt` object containing the messages to be used in the execution.
     * @param model The instance of `LLModel` that specifies the LLM to be used.
     * @param tools An optional list of `ToolDescriptor` objects that define the tools available for the execution.
     * @param hook Optional lifecycle hook invoked around model resolution and execution events.
     * @param executorService An optional `ExecutorService` that can be provided to control the execution context.
     * @return A list of `Message.Response` objects representing the responses generated by the LLM.
     */
    @JavaAPI
    @JvmOverloads
    public fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor> = emptyList(),
        hook: ExecuteHook? = null,
        executorService: ExecutorService? = null
    ): List<Message.Response> = runOnIOBoundDispatcher(executorService) {
        val hookable = this@PromptExecutor as? HookablePromptExecutor
        hookable?.execute(prompt, model, tools, hook) ?: execute(prompt, model, tools)
    }

    /**
     * Receives multiple independent choices from the LLM.
     * The method is implemented only for some specific providers which support multiple LLM choices.
     *
     * @param prompt The prompt containing input messages and parameters to guide the LLM execution.
     * @param model The LLM to be used for processing the prompt.
     * @param tools A list of `ToolDescriptor` objects that define the tools available for the execution.
     * @param hook Optional lifecycle hook invoked around model resolution and execution events.
     * @param executorService An optional `ExecutorService` that can be provided to control the execution context.
     * @return A list of `LLMChoice` objects representing the responses generated by the LLM.
     */
    @JavaAPI
    @JvmOverloads
    public fun executeMultipleChoices(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor> = emptyList(),
        hook: MultipleChoicesHook? = null,
        executorService: ExecutorService? = null
    ): List<LLMChoice> = runOnIOBoundDispatcher(executorService) {
        val hookable = this@PromptExecutor as? HookablePromptExecutor
        hookable?.executeMultipleChoices(prompt, model, tools, hook) ?: executeMultipleChoices(prompt, model, tools)
    }

    /**
     * Executes a given prompt using the specified language model (LLM) and tools,
     * providing the results as a synchronous stream of [StreamFrame] objects.
     *
     * @param prompt The [Prompt] object containing the input messages and parameters for the execution.
     * @param model The [LLModel] instance specifying the language model to be used.
     * @param tools An optional list of [ToolDescriptor] objects defining the tools available during execution. Defaults to an empty list.
     * @param hook Optional lifecycle hook invoked around model resolution and streaming events.
     * @return A [Publisher] that emits [StreamFrame] objects representing streamed responses generated by the LLM.
     */
    @JavaAPI
    @JvmOverloads
    public fun executeStreamingWithPublisher(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor> = emptyList(),
        hook: StreamingHook? = null,
    ): Publisher<StreamFrame> {
        val hookable = this as? HookablePromptExecutor
        return (hookable?.executeStreaming(prompt, model, tools, hook) ?: executeStreaming(prompt, model, tools))
            .asPublisher()
    }

    /**
     * Moderates the content of a given message with attachments using a specified LLM.
     *
     * @param model The LLM that will be used to perform the moderation.
     * @param executorService An optional `ExecutorService` that can be provided to control the execution context.
     * @param hook Optional lifecycle hook invoked around model resolution and moderation events.
     * @return A `ModerationResult` containing information about the moderation outcome,
     *         including flagged categories, scores, and whether the content is classified
     *         as harmful.
     */
    @JavaAPI
    @JvmOverloads
    public fun moderate(
        prompt: Prompt,
        model: LLModel,
        executorService: ExecutorService? = null,
        hook: ModerateHook? = null,
    ): ModerationResult = runOnIOBoundDispatcher(executorService) {
        val hookable = this@PromptExecutor as? HookablePromptExecutor
        hookable?.moderate(prompt, model, hook) ?: moderate(prompt, model)
    }

    /**
     * Retrieves a list of available models from all LLM clients managed by this executor.
     *
     * This method aggregates models from all configured LLM providers and clients,
     * returning a comprehensive list of available language models that can be used
     * with this executor.
     *
     * @param executorService An optional `ExecutorService` that can be provided to control the execution context.
     * @return A list of [LLModel] instances representing all available models.
     */
    @JavaAPI
    @JvmOverloads
    public fun models(executorService: ExecutorService? = null): List<LLModel> =
        runOnIOBoundDispatcher(executorService) {
            models()
        }

    /**
     * Companion object for [PromptExecutor].
     */
    public companion object {

        /**
         * Creates an [PromptExecutorBuilder] for constructing a [PromptExecutor].
         *
         * The concrete executor implementation is chosen automatically at build time based on
         * the registered clients — see [PromptExecutorBuilder.build] for the selection heuristic.
         *
         * Example usage in Java:
         * ```java
         * PromptExecutor executor = PromptExecutor.builder()
         *     .addClient(openAIClient)
         *     .addClient(anthropicClient)
         *     .build();
         * ```
         *
         * @return A new [PromptExecutorBuilder] instance.
         */
        @JvmStatic
        @JavaAPI
        public fun builder(): PromptExecutorBuilder = PromptExecutorBuilder()
    }
}
