package ai.koog.a2a.model

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject
import kotlin.jvm.JvmStatic
import kotlin.time.Clock
import kotlin.time.Instant

/**
 * Represents a single, stateful operation or conversation between a client and an agent.
 *
 * @property id A unique identifier (e.g. UUID) for the task, generated by the server for a new task.
 * @property contextId A server-generated unique identifier (e.g. UUID) for maintaining context across multiple related tasks or interactions.
 * @property status The current status of the task, including its state and a descriptive message.
 * @property history An array of messages exchanged during the task, representing the conversation history.
 * @property artifacts A collection of artifacts generated by the agent during the execution of the task.
 * @property metadata Optional metadata for extensions. The key is an extension-specific identifier.
 */
@Serializable
public data class Task(
    public val id: String,
    override val contextId: String,
    public val status: TaskStatus,
    public val history: List<Message>? = null,
    public val artifacts: List<Artifact>? = null,
    public val metadata: JsonObject? = null,
) : ResponseEvent, TaskEvent {
    override val taskId: String get() = id

    public companion object {
        @JvmStatic
        public const val KIND: String = "task"
    }
}

/**
 * An event sent by the agent to notify the client of a change in a task's status.
 * This is typically used in streaming or subscription models.
 *
 * @property taskId The ID of the task that was updated.
 * @property contextId The context ID associated with the task.
 * @property status The new status of the task.
 * @property metadata Optional metadata for extensions.
 */
@Serializable
public data class TaskStatusUpdateEvent(
    override val taskId: String,
    override val contextId: String,
    public val status: TaskStatus,
    public val metadata: JsonObject? = null,
) : TaskEvent {
    public companion object {
        @JvmStatic
        public const val KIND: String = "statusUpdate"
    }
}

/**
 * An event sent by the agent to notify the client that an artifact has been
 * generated or updated. This is typically used in streaming models.
 *
 * @property taskId The ID of the task this artifact belongs to.
 * @property contextId The context ID associated with the task.
 * @property artifact The artifact that was generated or updated.
 * @property append If true, the content of this artifact should be appended to a previously sent artifact with the same ID.
 * @property lastChunk If true, this is the final chunk of the artifact.
 * @property metadata Optional metadata for extensions.
 */
@Serializable
public data class TaskArtifactUpdateEvent(
    override val taskId: String,
    override val contextId: String,
    public val artifact: Artifact,
    public val append: Boolean? = null,
    public val lastChunk: Boolean? = null,
    public val metadata: JsonObject? = null,
) : TaskEvent {
    public companion object {
        @JvmStatic
        public const val KIND: String = "artifactUpdate"
    }
}

/**
 * Represents the status of a task at a specific point in time.
 *
 * @property state The current state of the task's lifecycle.
 * @property message An optional, human-readable message providing more details about the current status.
 * @property timestamp Timestamp indicating when this status was recorded.
 */
@Serializable
public data class TaskStatus(
    public val state: TaskState,
    public val message: Message? = null,
    public val timestamp: Instant? = Clock.System.now(),
)

/**
 * Defines the lifecycle states of a Task.
 *
 * @property terminal Indicates whether this is a terminal state.
 */
@Serializable
public enum class TaskState(public val terminal: Boolean) {
    /**
     * The task has been submitted and is awaiting execution.
     */
    TASK_STATE_SUBMITTED(terminal = false),

    /**
     * The agent is actively working on the task.
     */
    TASK_STATE_WORKING(terminal = false),

    /**
     * The task is paused and waiting for input from the user.
     */
    TASK_STATE_INPUT_REQUIRED(terminal = false),

    /**
     * The task has been successfully completed.
     */
    TASK_STATE_COMPLETED(terminal = true),

    /**
     * The task has been canceled by the user.
     */
    TASK_STATE_CANCELED(terminal = true),

    /**
     * The task failed due to an error during execution.
     */
    TASK_STATE_FAILED(terminal = true),

    /**
     *  The task was rejected by the agent and was not started.
     */
    TASK_STATE_REJECTED(terminal = true),

    /**
     * The task requires authentication to proceed.
     */
    TASK_STATE_AUTH_REQUIRED(terminal = false),

    /*
     * The task is in an unknown or indeterminate state.
     */
    TASK_STATE_UNKNOWN(terminal = false),
}

/**
 * Represents a file, data structure, or other resource generated by an agent during a task.
 *
 * @property artifactId A unique identifier (e.g. UUID) for the artifact within the scope of the task.
 * @property name An optional, human-readable name for the artifact.
 * @property description An optional, human-readable description of the artifact.
 * @property parts A list of content parts that make up the artifact.
 * @property extensions Optional URIs of extensions that are relevant to this artifact.
 * @property metadata Optional metadata for extensions. The key is an extension-specific identifier.
 */
@Serializable
public data class Artifact(
    public val artifactId: String,
    public val name: String? = null,
    public val description: String? = null,
    public val parts: List<Part>,
    public val extensions: List<String>? = null,
    public val metadata: JsonObject? = null,
)

