[versions]
kotlin = "2.2.20"
koog = "0.4.1"

[libraries]
# Koog (meta-dependency to get all core modules)
koog-all = { module = "ai.koog:koog-agents", version.ref = "koog" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
