{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-schema-generator-json/0.3.3-SNAPSHOT/kotlinx-schema-generator-json-0.3.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-schema-generator-json",
    "version": "0.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-generator-core",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-json",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT.klib",
          "size": 72756,
          "sha512": "057ea671bb42e5c3fceca66d4f196c7490e758003c3ec7fc1ddbb42f30a4b7971eb142e8fe9246f43eaabbda0f513ead3401809e56fa52adb78700c5a9ce3161",
          "sha256": "df107f689c0f227ab5ba9a1e71322d84d9ba0ad3cdcfc95601519b1573275fc9",
          "sha1": "beb701546e014c47db656fc4786470fd0da8ee93",
          "md5": "35f78b13e77305028289b80efccb9971"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-annotations",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-generator-core",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-schema-json",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT.klib",
          "url": "kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT.klib",
          "size": 72756,
          "sha512": "057ea671bb42e5c3fceca66d4f196c7490e758003c3ec7fc1ddbb42f30a4b7971eb142e8fe9246f43eaabbda0f513ead3401809e56fa52adb78700c5a9ce3161",
          "sha256": "df107f689c0f227ab5ba9a1e71322d84d9ba0ad3cdcfc95601519b1573275fc9",
          "sha1": "beb701546e014c47db656fc4786470fd0da8ee93",
          "md5": "35f78b13e77305028289b80efccb9971"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-schema-generator-json-js-0.3.3-SNAPSHOT-sources.jar",
          "size": 19683,
          "sha512": "357f1227fe71824ffa8d4b42af5ac67a5af520b00f851b819dbabe1cdfc478ecaa59f9d6552e5add4e6d908b14faae16521c27258b35d67dd418660a976d34c3",
          "sha256": "1460a400b213aed030f072bf7ce267907e9e7e7bf9768019da78afdeb7e4077d",
          "sha1": "d7fa5b158e8eb64cd53fc26056bdc53e14bc8ba3",
          "md5": "db04f032cfa18b9e8771b0091a9e3867"
        }
      ]
    }
  ]
}
